// Derived from the English catalogs by scripts/generate-message-pen.js.
export interface CatalogIds {
  validate: "type" | "required" | "minimum" | "maximum" | "exclusiveMinimum" | "exclusiveMaximum" | "multipleOf" | "minLength" | "maxLength" | "pattern" | "additionalProperties" | "minProperties" | "maxProperties" | "minItems" | "maxItems" | "uniqueItems" | "contains" | "items" | "allOf" | "anyOf" | "oneOf" | "not" | "format" | "if" | "then" | "else" | "false schema" | "$query" | "JQ2001" | "JQ2003";
  forms: "form/required" | "form/type" | "form/const" | "form/enum" | "form/minLength" | "form/maxLength" | "form/pattern" | "form/format" | "form/minimum" | "form/maximum" | "form/exclusiveMinimum" | "form/exclusiveMaximum" | "form/multipleOf" | "form/minItems" | "form/maxItems" | "form/uniqueItems" | "form/minProperties" | "form/maxProperties" | "x-form/assert" | "form/addItem" | "form/removeItem" | "form/jsonPlaceholder";
  contract: "contract/not-found" | "contract/method-not-allowed" | "contract/body-too-large" | "contract/unsupported-media" | "contract/malformed-json" | "contract/malformed-body" | "contract/invalid-input" | "contract/idempotency-key-required" | "contract/handler-failed" | "contract/idempotency-conflict" | "contract/invalid-output" | "contract/malformed-path" | "contract/malformed-query" | "contract/not-implemented" | "contract/precondition-failed" | "contract/invalid-header" | "contract/handler-error" | "contract/client-invalid-input" | "contract/network" | "contract/cancelled" | "contract/invalid-response" | "contract/key-storage-failed" | "contract/undeclared-response" | "contract/not-a-contract" | "contract/incompatible" | "contract/host-failed" | "contract/local-handler-failed" | "contract/unknown-operation" | "contract/port-timeout" | "contract/malformed-frame" | "contract/channel-closed" | "contract/not-a-stream" | "contract/invalid-snapshot" | "contract/seq-regression" | "contract/stream-error" | "contract/heartbeat-missed" | "contract/slow-consumer" | "contract/reconnect-exhausted";
  query: "query/reason" | "query/detail" | "query/item/sequence" | "query/item/empty" | "query/item/null" | "query/item/array" | "query/item/object" | "query/item/string" | "query/item/number" | "query/item/boolean" | "query/item/other" | "query/mixed-keys" | "query/unknown-operator" | "query/unknown-operator-suggest" | "query/unknown-operator-use" | "query/unknown-operator-none" | "query/use/head-of-reverse" | "query/use/jsonpath-filter" | "query/use/for-return" | "query/use/for-phrase" | "query/use/sort-objects" | "query/use/sort-scalars" | "query/use/entries-get" | "query/use/geo-parse-text" | "query/use/bbox-intersects" | "query/use/renderer" | "query/use/renderer-project" | "query/use/similarity" | "query/use/knn-desc" | "query/use/knn" | "query/use/top-k" | "query/use/resample-fill" | "query/use/resample-locf" | "query/use/resample-linear" | "query/use/rolling-mean" | "query/use/trim" | "query/use/truncate" | "query/phrase-keys" | "query/phrase-alone" | "query/operands-array" | "query/operands-exactly" | "query/operands-at-least" | "query/operands-range" | "query/variable-name-expected" | "query/variable-name-invalid" | "query/variable-duplicate" | "query/bindings-object" | "query/bindings-empty" | "query/extended-let" | "query/extended-quantifier" | "query/window-kind" | "query/window-size-required" | "query/window-size" | "query/window-step" | "query/window-required" | "query/for-key" | "query/for-in-required" | "query/for-at" | "query/for-allowing-empty" | "query/orderby-spec" | "query/orderby-spec-key" | "query/orderby-spec-key-required" | "query/orderby-dir" | "query/orderby-empty" | "query/collation-name" | "query/collation-unregistered" | "query/fold-binding" | "query/as-object" | "query/as-empty" | "query/as-unbound" | "query/count-variable" | "query/map-entry" | "query/call-arguments" | "query/call-unregistered" | "query/apply-arguments" | "query/apply-mode" | "query/document-value" | "query/invalid-path" | "query/invalid-path-detail" | "query/unbound-variable" | "query/unbound-variable-closed" | "query/version-unknown" | "query/version-envelope" | "query/schema-no-compiler" | "query/schema-invalid" | "query/schema-no-predicate" | "query/depth-limit" | "query/spec-member-required" | "query/spec-invalid" | "query/date-pattern" | "query/time-bucket-invalid" | "query/lexical-arguments" | "query/lexical-unregistered" | "query/lexical-rejected" | "query/lexical-no-request" | "query/series-spec-object" | "query/series-spec-member" | "query/series-spec-member-suggest" | "query/series-member-enum" | "query/series-member-number" | "query/series-member-instant" | "query/series-member-duration" | "query/series-member-path" | "query/series-member-path-detail" | "query/series-member-not-path" | "query/series-member-whole-row" | "query/series-member-singular" | "query/series-zone" | "query/series-zone-provider" | "query/series-calendar" | "query/expected-string" | "query/expected-number" | "query/cast-string" | "query/cast-number" | "query/not-json-number" | "query/arithmetic-operand" | "query/round-precision" | "query/format-picture" | "query/picture/separator-twice" | "query/picture/decimal-twice" | "query/picture/percent" | "query/picture/no-digit" | "query/picture/passive-inside" | "query/picture/grouping-twice" | "query/picture/grouping-edge" | "query/picture/digit-order" | "query/picture/exponent-twice" | "query/picture/exponent-percent" | "query/picture/exponent-digits" | "query/decimal-format-type" | "query/decimal-format-unknown" | "query/decimal-format-invalid" | "query/decimal-format-record" | "query/decimal-format-member" | "query/decimal-format-character" | "query/decimal-format-zero" | "query/decimal-format-clash" | "query/quantity-unit" | "query/aggregate-not-number" | "query/aggregate-null" | "query/minmax-mixed" | "query/sort-mixed" | "query/regex-invalid" | "query/replace-empty-match" | "query/range-bounds" | "query/range-guard" | "query/index-of-item" | "query/expected-datetime" | "query/no-date-component" | "query/no-time-component" | "query/calendar-unit" | "query/expected-duration" | "query/expected-units" | "query/expected-date-pattern" | "query/date-names" | "query/datetime-epoch" | "query/datetime-range" | "query/span-no-date" | "query/expected-bucket-width" | "query/expected-geo" | "query/expected-wkt" | "query/expected-geohash" | "query/geohash-precision" | "query/simplify-tolerance" | "query/expected-vector" | "query/expected-vector-item" | "query/expected-series" | "query/expected-interval" | "query/member-cardinality" | "query/groupby-key" | "query/lexical-text" | "query/idiv-zero" | "query/mod-zero" | "query/ebv-sequence" | "query/map-key" | "query/orderby-key" | "query/orderby-number-string" | "query/orderby-string-number" | "query/external-unbound" | "query/assert-failed" | "query/assert-failed-item" | "query/as-failed" | "query/as-failed-item" | "query/fold-limit" | "query/phrase-limit" | "query/steps-limit" | "query/result-limit" | "query/function-threw" | "query/operator-threw" | "query/input-undefined" | "query/lexical-threw" | "query/lexical-result";
}
export interface MessageParameters {
  "type": "type" | "types";
  "required": "missingProperty";
  "minimum": "comparison" | "limit";
  "maximum": "comparison" | "limit";
  "exclusiveMinimum": "comparison" | "limit";
  "exclusiveMaximum": "comparison" | "limit";
  "multipleOf": "multipleOf";
  "minLength": "limit";
  "maxLength": "limit";
  "pattern": "pattern";
  "additionalProperties": "additionalProperty";
  "minProperties": "limit";
  "maxProperties": "limit";
  "minItems": "limit";
  "maxItems": "limit";
  "uniqueItems": never;
  "contains": never;
  "items": never;
  "allOf": never;
  "anyOf": never;
  "oneOf": never;
  "not": never;
  "format": "format";
  "if": never;
  "then": never;
  "else": never;
  "false schema": never;
  "$query": "code" | "docPath";
  "JQ2001": "code" | "docPath";
  "JQ2003": "code" | "docPath";
  "form/required": never;
  "form/type": "type";
  "form/const": "constValue";
  "form/enum": "enumValues";
  "form/minLength": "len" | "limit";
  "form/maxLength": "len" | "limit";
  "form/pattern": "pattern";
  "form/format": "format";
  "form/minimum": "limit";
  "form/maximum": "limit";
  "form/exclusiveMinimum": "limit";
  "form/exclusiveMaximum": "limit";
  "form/multipleOf": "multipleOf";
  "form/minItems": "limit";
  "form/maxItems": "limit";
  "form/uniqueItems": never;
  "form/minProperties": "limit";
  "form/maxProperties": "limit";
  "x-form/assert": never;
  "form/addItem": never;
  "form/removeItem": never;
  "form/jsonPlaceholder": never;
  "contract/not-found": never;
  "contract/method-not-allowed": "allow";
  "contract/body-too-large": "limit" | "op";
  "contract/unsupported-media": "media" | "op";
  "contract/malformed-json": "op";
  "contract/malformed-body": "op";
  "contract/invalid-input": "op";
  "contract/idempotency-key-required": "op";
  "contract/handler-failed": "op";
  "contract/idempotency-conflict": "kind" | "op";
  "contract/invalid-output": "op";
  "contract/malformed-path": never;
  "contract/malformed-query": never;
  "contract/not-implemented": "op";
  "contract/precondition-failed": "op";
  "contract/invalid-header": "header" | "op";
  "contract/handler-error": "code" | "op";
  "contract/client-invalid-input": "op";
  "contract/network": "name" | "op";
  "contract/cancelled": "op";
  "contract/invalid-response": "op";
  "contract/key-storage-failed": "op";
  "contract/undeclared-response": "op" | "status";
  "contract/not-a-contract": "id";
  "contract/incompatible": "client" | "id" | "server";
  "contract/host-failed": "op";
  "contract/local-handler-failed": "op";
  "contract/unknown-operation": never;
  "contract/port-timeout": "ms" | "op";
  "contract/malformed-frame": "op";
  "contract/channel-closed": "op";
  "contract/not-a-stream": "op";
  "contract/invalid-snapshot": "op";
  "contract/seq-regression": "op";
  "contract/stream-error": "code" | "op";
  "contract/heartbeat-missed": "ms" | "op";
  "contract/slow-consumer": "op";
  "contract/reconnect-exhausted": "attempts" | "lastCode" | "op";
  "query/reason": "reason";
  "query/detail": "detail";
  "query/item/sequence": "count";
  "query/item/empty": never;
  "query/item/null": never;
  "query/item/array": never;
  "query/item/object": never;
  "query/item/string": never;
  "query/item/number": never;
  "query/item/boolean": never;
  "query/item/other": "type";
  "query/mixed-keys": never;
  "query/unknown-operator": "key";
  "query/unknown-operator-suggest": "key" | "suggestion";
  "query/unknown-operator-use": "key" | "use";
  "query/unknown-operator-none": "key";
  "query/use/head-of-reverse": never;
  "query/use/jsonpath-filter": never;
  "query/use/for-return": never;
  "query/use/for-phrase": never;
  "query/use/sort-objects": never;
  "query/use/sort-scalars": never;
  "query/use/entries-get": never;
  "query/use/geo-parse-text": never;
  "query/use/bbox-intersects": never;
  "query/use/renderer": never;
  "query/use/renderer-project": never;
  "query/use/similarity": never;
  "query/use/knn-desc": never;
  "query/use/knn": never;
  "query/use/top-k": never;
  "query/use/resample-fill": never;
  "query/use/resample-locf": never;
  "query/use/resample-linear": never;
  "query/use/rolling-mean": never;
  "query/use/trim": never;
  "query/use/truncate": never;
  "query/phrase-keys": "keys";
  "query/phrase-alone": "key";
  "query/operands-array": "op";
  "query/operands-exactly": "count" | "min" | "op";
  "query/operands-at-least": "count" | "min" | "op";
  "query/operands-range": "count" | "max" | "min" | "op";
  "query/variable-name-expected": never;
  "query/variable-name-invalid": "name";
  "query/variable-duplicate": "name";
  "query/bindings-object": "clause";
  "query/bindings-empty": "clause";
  "query/extended-let": never;
  "query/extended-quantifier": never;
  "query/window-kind": never;
  "query/window-size-required": never;
  "query/window-size": never;
  "query/window-step": never;
  "query/window-required": never;
  "query/for-key": "key";
  "query/for-in-required": never;
  "query/for-at": never;
  "query/for-allowing-empty": never;
  "query/orderby-spec": never;
  "query/orderby-spec-key": "key";
  "query/orderby-spec-key-required": never;
  "query/orderby-dir": never;
  "query/orderby-empty": never;
  "query/collation-name": never;
  "query/collation-unregistered": "name";
  "query/fold-binding": never;
  "query/as-object": never;
  "query/as-empty": never;
  "query/as-unbound": "name";
  "query/count-variable": never;
  "query/map-entry": never;
  "query/call-arguments": never;
  "query/call-unregistered": "name";
  "query/apply-arguments": never;
  "query/apply-mode": never;
  "query/document-value": "type";
  "query/invalid-path": "path";
  "query/invalid-path-detail": "detail" | "path";
  "query/unbound-variable": "declared" | "name";
  "query/unbound-variable-closed": "name";
  "query/version-unknown": "version";
  "query/version-envelope": never;
  "query/schema-no-compiler": never;
  "query/schema-invalid": "detail";
  "query/schema-no-predicate": never;
  "query/depth-limit": "depth" | "limit";
  "query/spec-member-required": "member" | "name";
  "query/spec-invalid": "detail" | "name";
  "query/date-pattern": "detail";
  "query/time-bucket-invalid": "detail";
  "query/lexical-arguments": never;
  "query/lexical-unregistered": "name";
  "query/lexical-rejected": never;
  "query/lexical-no-request": never;
  "query/series-spec-object": "got" | "operator";
  "query/series-spec-member": "allowed" | "name" | "operator";
  "query/series-spec-member-suggest": "allowed" | "name" | "operator" | "suggestion";
  "query/series-member-enum": "allowed" | "got" | "member";
  "query/series-member-number": "got" | "member";
  "query/series-member-instant": "got" | "member";
  "query/series-member-duration": "got" | "member";
  "query/series-member-path": "got" | "member";
  "query/series-member-path-detail": "detail" | "member";
  "query/series-member-not-path": "member";
  "query/series-member-whole-row": "member";
  "query/series-member-singular": "member";
  "query/series-zone": "got";
  "query/series-zone-provider": "zone";
  "query/series-calendar": "detail";
  "query/expected-string": "got";
  "query/expected-number": "got";
  "query/cast-string": "got";
  "query/cast-number": "got";
  "query/not-json-number": "value";
  "query/arithmetic-operand": "got";
  "query/round-precision": "got" | "op";
  "query/format-picture": "picture" | "rule";
  "query/picture/separator-twice": never;
  "query/picture/decimal-twice": never;
  "query/picture/percent": never;
  "query/picture/no-digit": never;
  "query/picture/passive-inside": never;
  "query/picture/grouping-twice": never;
  "query/picture/grouping-edge": never;
  "query/picture/digit-order": never;
  "query/picture/exponent-twice": never;
  "query/picture/exponent-percent": never;
  "query/picture/exponent-digits": never;
  "query/decimal-format-type": "got" | "op";
  "query/decimal-format-unknown": "name" | "op";
  "query/decimal-format-invalid": "op" | "rule";
  "query/decimal-format-record": never;
  "query/decimal-format-member": "name";
  "query/decimal-format-character": "name";
  "query/decimal-format-zero": "char";
  "query/decimal-format-clash": "char";
  "query/quantity-unit": "op" | "unit";
  "query/aggregate-not-number": "got";
  "query/aggregate-null": never;
  "query/minmax-mixed": "got";
  "query/sort-mixed": "got";
  "query/regex-invalid": "pattern";
  "query/replace-empty-match": "pattern";
  "query/range-bounds": "got";
  "query/range-guard": "count" | "limit";
  "query/index-of-item": "got";
  "query/expected-datetime": "got";
  "query/no-date-component": "value";
  "query/no-time-component": "value";
  "query/calendar-unit": "got";
  "query/expected-duration": "got";
  "query/expected-units": "got";
  "query/expected-date-pattern": "got";
  "query/date-names": "token";
  "query/datetime-epoch": "got";
  "query/datetime-range": "value";
  "query/span-no-date": never;
  "query/expected-bucket-width": "got";
  "query/expected-geo": "got";
  "query/expected-wkt": "got";
  "query/expected-geohash": "got";
  "query/geohash-precision": "got";
  "query/simplify-tolerance": "got";
  "query/expected-vector": "got";
  "query/expected-vector-item": "got" | "index";
  "query/expected-series": "got";
  "query/expected-interval": "got";
  "query/member-cardinality": "count" | "name";
  "query/groupby-key": "got";
  "query/lexical-text": never;
  "query/idiv-zero": never;
  "query/mod-zero": never;
  "query/ebv-sequence": never;
  "query/map-key": "got";
  "query/orderby-key": "got";
  "query/orderby-number-string": never;
  "query/orderby-string-number": never;
  "query/external-unbound": "name";
  "query/assert-failed": "got";
  "query/assert-failed-item": "got" | "index";
  "query/as-failed": "got" | "name";
  "query/as-failed-item": "got" | "index" | "name";
  "query/fold-limit": "limit";
  "query/phrase-limit": "limit";
  "query/steps-limit": "limit";
  "query/result-limit": "count" | "limit";
  "query/function-threw": "detail" | "name";
  "query/operator-threw": "detail" | "name";
  "query/input-undefined": never;
  "query/lexical-threw": never;
  "query/lexical-result": never;
}
