// Derived from the English catalogs by scripts/generate-message-pen.js.
export interface CatalogIds {
  validate: "type" | "required" | "minimum" | "maximum" | "exclusiveMinimum" | "exclusiveMaximum" | "multipleOf" | "minLength" | "maxLength" | "pattern" | "additionalProperties" | "minProperties" | "maxProperties" | "minItems" | "maxItems" | "uniqueItems" | "contains" | "items" | "allOf" | "anyOf" | "oneOf" | "not" | "format" | "if" | "then" | "else" | "false schema" | "$query" | "JQ2001" | "JQ2003";
  forms: "form/required" | "form/type" | "form/const" | "form/enum" | "form/minLength" | "form/maxLength" | "form/pattern" | "form/format" | "form/minimum" | "form/maximum" | "form/exclusiveMinimum" | "form/exclusiveMaximum" | "form/multipleOf" | "form/minItems" | "form/maxItems" | "form/uniqueItems" | "form/minProperties" | "form/maxProperties" | "x-form/assert" | "form/addItem" | "form/removeItem";
  contract: "contract/not-found" | "contract/method-not-allowed" | "contract/body-too-large" | "contract/unsupported-media" | "contract/malformed-json" | "contract/invalid-input" | "contract/idempotency-key-required" | "contract/handler-failed" | "contract/idempotency-conflict" | "contract/invalid-output" | "contract/malformed-path" | "contract/malformed-query" | "contract/not-implemented" | "contract/precondition-failed" | "contract/invalid-header" | "contract/handler-error" | "contract/client-invalid-input" | "contract/network" | "contract/cancelled" | "contract/invalid-response" | "contract/key-storage-failed" | "contract/undeclared-response" | "contract/not-a-contract" | "contract/incompatible" | "contract/host-failed" | "contract/local-handler-failed" | "contract/unknown-operation" | "contract/port-timeout" | "contract/malformed-frame" | "contract/channel-closed" | "contract/not-a-stream" | "contract/invalid-snapshot" | "contract/seq-regression" | "contract/stream-error" | "contract/heartbeat-missed" | "contract/slow-consumer" | "contract/reconnect-exhausted";
}
export interface MessageParameters {
  "type": "type" | "types";
  "required": "missingProperty";
  "minimum": "comparison" | "limit";
  "maximum": "comparison" | "limit";
  "exclusiveMinimum": "comparison" | "limit";
  "exclusiveMaximum": "comparison" | "limit";
  "multipleOf": "multipleOf";
  "minLength": "limit";
  "maxLength": "limit";
  "pattern": "pattern";
  "additionalProperties": "additionalProperty";
  "minProperties": "limit";
  "maxProperties": "limit";
  "minItems": "limit";
  "maxItems": "limit";
  "uniqueItems": never;
  "contains": never;
  "items": never;
  "allOf": never;
  "anyOf": never;
  "oneOf": never;
  "not": never;
  "format": "format";
  "if": never;
  "then": never;
  "else": never;
  "false schema": never;
  "$query": "code" | "docPath";
  "JQ2001": "code" | "docPath";
  "JQ2003": "code" | "docPath";
  "form/required": never;
  "form/type": "type";
  "form/const": "constValue";
  "form/enum": "enumValues";
  "form/minLength": "len" | "limit";
  "form/maxLength": "len" | "limit";
  "form/pattern": "pattern";
  "form/format": "format";
  "form/minimum": "limit";
  "form/maximum": "limit";
  "form/exclusiveMinimum": "limit";
  "form/exclusiveMaximum": "limit";
  "form/multipleOf": "multipleOf";
  "form/minItems": "limit";
  "form/maxItems": "limit";
  "form/uniqueItems": never;
  "form/minProperties": "limit";
  "form/maxProperties": "limit";
  "x-form/assert": never;
  "form/addItem": never;
  "form/removeItem": never;
  "contract/not-found": never;
  "contract/method-not-allowed": "allow";
  "contract/body-too-large": "limit" | "op";
  "contract/unsupported-media": "media" | "op";
  "contract/malformed-json": "op";
  "contract/invalid-input": "op";
  "contract/idempotency-key-required": "op";
  "contract/handler-failed": "op";
  "contract/idempotency-conflict": "kind" | "op";
  "contract/invalid-output": "op";
  "contract/malformed-path": never;
  "contract/malformed-query": never;
  "contract/not-implemented": "op";
  "contract/precondition-failed": "op";
  "contract/invalid-header": "header" | "op";
  "contract/handler-error": "code" | "op";
  "contract/client-invalid-input": "op";
  "contract/network": "name" | "op";
  "contract/cancelled": "op";
  "contract/invalid-response": "op";
  "contract/key-storage-failed": "op";
  "contract/undeclared-response": "op" | "status";
  "contract/not-a-contract": "id";
  "contract/incompatible": "client" | "id" | "server";
  "contract/host-failed": "op";
  "contract/local-handler-failed": "op";
  "contract/unknown-operation": never;
  "contract/port-timeout": "ms" | "op";
  "contract/malformed-frame": "op";
  "contract/channel-closed": "op";
  "contract/not-a-stream": "op";
  "contract/invalid-snapshot": "op";
  "contract/seq-regression": "op";
  "contract/stream-error": "code" | "op";
  "contract/heartbeat-missed": "ms" | "op";
  "contract/slow-consumer": "op";
  "contract/reconnect-exhausted": "attempts" | "lastCode" | "op";
}
