// Generated by @jarenjs/db entityEmitModel + @jarenjs/emit from
// test/db/emit-model-fixture.js — regenerate with
// `node scripts/generate-db-fixture.js`. test/db/emit-model.test.js
// fails if this drifts from what the generator produces.

/**
 * An RFC 3339 string branded for the date operators;
 * structurally identical to the @jarenjs/linq brand.
 */
export type DateTime = string & { __jarenTag: "date-time"; };

export interface User {
  id: string;
  email: string;
  name?: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  age?: number;
  active?: boolean;
  role?: "admin" | "user";
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  joined?: DateTime;
  /**
   * The optimistic-concurrency token (§11.5):
   * engine-owned, bumped on every successful write.
   */
  rev?: number;
  profile?: { bio?: string; links?: Array<string>; };
  /**
   * The oneToMany relation to Post; present only
   * when a graph load included it.
   */
  posts?: Array<Post>;
  /**
   * The manyToMany relation to Label; present only
   * when a graph load included it.
   */
  labels?: Array<Label>;
}


/**
 * What create()/add() accept for User: defaulted and
 * generated members are optional; relation projections are not
 * writable (many-to-many membership arrays are).
 */
export interface UserInput {
  /**
   * Defaulted ("uuid");
   * optional for a caller, present after the write.
   */
  id?: string;
  email: string;
  name?: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  age?: number;
  active?: boolean;
  /**
   * Defaulted ({"value":"user"});
   * optional for a caller, present after the write.
   */
  role?: "admin" | "user";
  /**
   * Schema constraints this type cannot express: format="date-time"
   */
  joined?: string;
  /**
   * The optimistic-concurrency token (§11.5):
   * engine-owned, bumped on every successful write.
   */
  rev?: number;
  profile?: { bio?: string; links?: Array<string>; };
  /**
   * Membership rows to attach: target keys or documents.
   */
  labels?: Array<string | Label>;
}


export interface Post {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  pid: number;
  title?: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  stars?: number;
  /**
   * Schema constraints this type cannot express: format="date"
   */
  published?: DateTime;
  authorId: string;
  /**
   * The oneToOne relation to User; present only
   * when a graph load included it.
   */
  author?: User;
}


/**
 * What create()/add() accept for Post: defaulted and
 * generated members are optional; relation projections are not
 * writable (many-to-many membership arrays are).
 */
export interface PostInput {
  /**
   * Defaulted ("auto");
   * optional for a caller, present after the write.
   */
  pid?: number;
  title?: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  stars?: number;
  /**
   * Schema constraints this type cannot express: format="date"
   */
  published?: string;
  authorId: string;
}


export interface Label {
  name: string;
}


/**
 * What create()/add() accept for Label: defaulted and
 * generated members are optional; relation projections are not
 * writable (many-to-many membership arrays are).
 */
export interface LabelInput {
  name: string;
}


export interface Grade {
  student: string;
  course: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  score?: number;
}


/**
 * What create()/add() accept for Grade: defaulted and
 * generated members are optional; relation projections are not
 * writable (many-to-many membership arrays are).
 */
export interface GradeInput {
  student: string;
  course: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  score?: number;
}


/**
 * Entity name to document shape.
 */
export interface Entities {
  User: User;
  Post: Post;
  Label: Label;
  Grade: Grade;
}


/**
 * Entity name to input shape.
 */
export interface EntityInputs {
  User: UserInput;
  Post: PostInput;
  Label: LabelInput;
  Grade: GradeInput;
}


/**
 * The typed-store binding: pass this to TypedStore<…> from
 * '@jarenjs/db/typed'.
 */
export interface EntityMetaMap {
  User: { doc: User; input: UserInput; key: string; relations: { posts: { entity: "Post"; doc: Post; many: true; }; labels: { entity: "Label"; doc: Label; many: true; }; }; };
  Post: { doc: Post; input: PostInput; key: number; relations: { author: { entity: "User"; doc: User; many: false; }; }; };
  Label: { doc: Label; input: LabelInput; key: string; relations: { }; };
  Grade: { doc: Grade; input: GradeInput; key: { student: string; course: string; }; relations: { }; };
}


