// Generated by @jarenjs/emit from test/emit/corpus.js — regenerate with
// `node scripts/generate-emit-fixture.js`. test/emit/agreement.test.js
// fails if this drifts from what the generator produces.

/**
 * Schema constraints this type cannot express: patternProperties=["^x"]
 */
export interface Patterned {
  [key: string]: number | string;
}


export interface Account {
  /**
   * Schema constraints this type cannot express: minLength=3
   */
  id: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  age?: number;
  role?: "admin" | "user";
  tags?: Array<string>;
  [key: string]: unknown;
}


export interface Strict {
  kind: string;
}


export type Label = string;

export interface Node {
  label: Label;
  children?: Array<Node>;
  [key: string]: unknown;
}


export interface Config {
  host: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  port: number;
  name: string;
  [key: string]: unknown;
}


/**
 * Accepted input for Config: the shape before normalization, where defaulted members may be absent and coercible values may still be in their transport form.
 */
export interface ConfigInput {
  host?: string | number | boolean;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  port?: number | string;
  name: string | number | boolean;
  [key: string]: unknown;
}


export type Uuid = string;

export type Id = Uuid;

export interface Base {
  id: string;
  [key: string]: unknown;
}


export type Wide = Base & { extra: number; [key: string]: unknown; };

/**
 * Schema constraints this type cannot express: minItems=1, maxItems=4
 */
export type Pair = [string, number?, ...Array<unknown>];

/**
 * Schema constraints this type cannot express: minItems=2
 */
export type Exact = [string, number];

export type Loose = { a: string; [key: string]: unknown; } | Array<unknown> | string | number | boolean | null;

export type Empty = Record<string, never>;

export interface Level {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  level: 1 | 2 | 3;
  [key: string]: unknown;
}


/**
 * Accepted input for Level: the shape before normalization, where defaulted members may be absent and coercible values may still be in their transport form.
 */
export interface LevelInput {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  level: 1 | 2 | 3 | string;
  [key: string]: unknown;
}


export interface Job {
  cmd: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  retries: number;
  [key: string]: unknown;
}


/**
 * Accepted input for Job: the shape before normalization, where defaulted members may be absent and coercible values may still be in their transport form.
 */
export interface JobInput {
  cmd: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  retries?: number;
  [key: string]: unknown;
}


export interface Choice {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  port: number;
  opt?: { mode?: string; level?: number; [key: string]: unknown; } | string;
  [key: string]: unknown;
}


/**
 * Accepted input for Choice: the shape before normalization, where defaulted members may be absent and coercible values may still be in their transport form.
 */
export interface ChoiceInput {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  port?: number | string;
  opt?: { mode?: string; level?: number; [key: string]: unknown; } | string;
  [key: string]: unknown;
}


export type Anything = unknown;

