// Generated by @jarenjs/emit from test/emit/corpus.js — regenerate with
// `node scripts/generate-emit-fixture.js`. test/emit/agreement.test.js
// fails if this drifts from what the generator produces.

export interface Account {
  /**
   * Schema constraints this type cannot express: minLength=3
   */
  id: string;
  age?: number;
  role?: "admin" | "user";
  tags?: Array<string>;
  [key: string]: unknown;
}


export interface Strict {
  kind: string;
}


export type Label = string;

export interface Node {
  label: Label;
  children?: Array<Node>;
  [key: string]: unknown;
}


export interface Config {
  host: string;
  port: number;
  name: string;
  [key: string]: unknown;
}


/**
 * Accepted input for Config: the shape before normalization, where defaulted members may be absent and coercible values may still be in their transport form.
 */
export interface ConfigInput {
  host?: string | number | boolean;
  port?: number | string;
  name: string | number | boolean;
  [key: string]: unknown;
}


