// Generated by @jarenjs/emit from test/emit/corpus.js — regenerate with
// `node scripts/generate-emit-fixture.js`. test/emit/agreement.test.js
// fails if this drifts from what the generator produces.

export interface Account {
  /**
   * Schema constraints this type cannot express: minLength=3
   */
  id: string;
  age?: number;
  role?: "admin" | "user";
  tags?: Array<string>;
}


export type Label = string;

export interface Node {
  label: Label;
  children?: Array<Node>;
}


