import { compileLexical, type LexicalDefinition, type LexicalIdentity } from '@jarenjs/core/search';
import { createArrayRangeProvider } from '@jarenjs/core/range';
import { createSearchResource } from '@jarenjs/app/search';
import { createDbSearch, createDbSearchStorage, type DbSearch } from '@jarenjs/db/search';
import { createLexicalRangeProvider } from '@jarenjs/linq/db';
import { createLexicalProvider, compileJsonQuery } from '@jarenjs/json/query';
import { from } from '@jarenjs/linq';
const definition: LexicalDefinition = { version: 1, fields: ['title'] };
const identity: LexicalIdentity = { generation: 1, sourceRevision: 'revision-1' };
const index = compileLexical(definition).create(); index.rebuild([{ id: 'a', title: 'tea' }], identity);
const restored = index.restore(index.snapshot(), { sourceRevision: 'revision-1' });
const provider = createLexicalProvider(index);
const result = compileJsonQuery({ $lexical: ['catalog', 'tea', {}] }, { lexicalProviders: { catalog: provider } })(null);
const doc = from([{ text: 'tea' }]).select(row => row.text.lexical('catalog', {})).toDocument();
const resource = createSearchResource(definition, { workerFactory: () => ({ request: async () => ({}), dispose() {} }) });
resource.build([], { generation: 1, requestId: 'build-1', sourceRevision: 'revision-1' });
resource.dispose(); createArrayRangeProvider([]).dispose();
declare const source: DbSearch;
createLexicalRangeProvider(source, 'tea', {}, { maxMatches: 100 });
void [createDbSearch, createDbSearchStorage, restored, result, doc];
