// Generated by @jarenjs/emit from test/linq/schema-corpus.js (each entry's
// EMITTED document) — regenerate with
// `node scripts/generate-schema-pen-fixture.js`. test/linq/schema-pen.test.js
// fails if this drifts from what the generator produces.

export interface Account {
  /**
   * Schema constraints this type cannot express: minLength=3
   */
  id: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  age?: number;
  role?: "admin" | "user";
  tags?: Array<string>;
  [key: string]: unknown;
}


export interface Strict {
  kind: string;
}


export interface Config {
  host: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  port: number;
  name: string;
  [key: string]: unknown;
}


/**
 * Accepted input for Config: the shape before normalization, where defaulted members may be absent and coercible values may still be in their transport form.
 */
export interface ConfigInput {
  host?: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  port?: number;
  name: string;
  [key: string]: unknown;
}


export type Uuid = string;

export type Id = Uuid;

/**
 * Schema constraints this type cannot express: minItems=2
 */
export type Exact = [string, number];

export type Empty = Record<string, never>;

export interface Job {
  cmd: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  retries: number;
  [key: string]: unknown;
}


/**
 * Accepted input for Job: the shape before normalization, where defaulted members may be absent and coercible values may still be in their transport form.
 */
export interface JobInput {
  cmd: string;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  retries?: number;
  [key: string]: unknown;
}


export interface Scalars {
  s: string;
  n: number;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  i: number;
  b: boolean;
  z: null;
}


export interface Literals {
  kind: "a";
  on: true;
  n: 1;
}


export interface Enums {
  role: "admin" | "user";
  mood: "up" | "down" | null;
  tag?: "x" | null;
}


export interface Nullables {
  name: string | null;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  age?: number | null;
}


export interface StringRules {
  /**
   * Schema constraints this type cannot express: format="uuid"
   */
  id: string;
  /**
   * Schema constraints this type cannot express: format="email"
   */
  mail: string;
  /**
   * Schema constraints this type cannot express: format="uri"
   */
  site: string;
  /**
   * Schema constraints this type cannot express: minLength=4, maxLength=4
   */
  code: string;
  /**
   * Schema constraints this type cannot express: minLength=1, maxLength=20, pattern="^[a-z-]+$"
   */
  slug: string;
}


export interface NumberRules {
  /**
   * Schema constraints this type cannot express: minimum=0, maximum=10
   */
  a: number;
  /**
   * Schema constraints this type cannot express: type="integer", exclusiveMinimum=0, exclusiveMaximum=5
   */
  b: number;
  /**
   * Schema constraints this type cannot express: multipleOf=0.5
   */
  c: number;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  d: number;
}


/**
 * An RFC 3339 string branded for the date operators;
 * structurally identical to the @jarenjs/linq brand.
 */
export type DateTime = string & { __jarenTag: "date-time"; };

export interface Dates {
  at: DateTime;
  on: DateTime;
  /**
   * Schema constraints this type cannot express: format="time"
   */
  t: string;
  /**
   * Schema constraints this type cannot express: format="duration"
   */
  d: string;
  seen?: DateTime | null;
  stamps?: Array<DateTime>;
}


export interface ArrayRules {
  /**
   * Schema constraints this type cannot express: minItems=1, maxItems=3, uniqueItems=true
   */
  tags: Array<string>;
  /**
   * Schema constraints this type cannot express: minItems=2, maxItems=2
   */
  pair: Array<number>;
  /**
   * Schema constraints this type cannot express: contains={"const":0}
   */
  has: Array<number>;
}


export interface Tuples {
  /**
   * Schema constraints this type cannot express: minItems=2
   */
  open: [string, number, ...Array<unknown>];
  /**
   * Schema constraints this type cannot express: minItems=1
   */
  tail: [string, ...Array<boolean>];
  /**
   * Schema constraints this type cannot express: minItems=2
   */
  exact: [string, number];
}


export interface Dict {
  [key: string]: number;
}


export interface Either {
  v: string | number;
  w?: { a: string; } | { b: number; };
}


export type Shape = { kind: "circle"; r: number; } | { kind: "square"; side: number; };

export type Both = { a: string; [key: string]: unknown; } & { b: number; [key: string]: unknown; };

export interface Node {
  label: string;
  children?: Array<Node>;
}


export type Tree = Node;

export interface Node2 {
  label: string;
  children?: Array<Node2>;
}


export interface Linked {
  head: Node2;
  tail?: Node2;
}


export interface Conditional {
  k: string;
  v: unknown;
  [key: string]: unknown;
}


export interface Wrapped {
  meta: { a?: string; [key: string]: unknown; };
  anything: unknown;
  nothing?: never;
  yes?: unknown;
}


/**
 * Schema constraints this type cannot express: minProperties=1, maxProperties=9, dependentRequired={"a":["b"]}
 */
export interface Members {
  a: string;
  b?: number;
  [key: string]: unknown;
}


/**
 * Schema constraints this type cannot express: patternProperties=["^x-"]
 */
export interface Patterned {
  id: string;
  [key: string]: number | string;
}


/**
 * Schema constraints this type cannot express: propertyNames={"type":"string","pattern":"^[a-z]+$"}
 */
export interface Keyed {
  [key: string]: unknown;
}


export interface Derived {
  one: { id: string; age?: number; email?: string; };
  two?: { name: string; };
}


/**
 * Schema constraints this type cannot express: $query={"$eq":["$.total",{"$sum":"$.lines[*].amount"}]}
 */
export interface Invoice {
  lines: Array<{ amount: number; }>;
  total: number;
}


/**
 * Schema constraints this type cannot express: $query={"$and":[{"$le":["$.start","$.end"]},{"$every":{"l":"$.lines[*]"},"$satisfies":{"$gt":["$l.qty",0]}}]}
 */
export interface Order {
  currency: string;
  start: DateTime;
  end: DateTime;
  lines: Array<{ qty: number; currency: string; }>;
}


export interface Coerced {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  port: number;
  on?: boolean;
  name: string;
  ratio: number;
  label?: string | null;
}


/**
 * Accepted input for Coerced: the shape before normalization, where defaulted members may be absent and coercible values may still be in their transport form.
 */
export interface CoercedInput {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  port: number | string;
  on?: boolean | string;
  name: string;
  ratio?: number | string;
  label?: string | null;
}


export interface Level {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  level: 1 | 2 | 3;
  role?: "admin" | "user" | null;
}


/**
 * Accepted input for Level: the shape before normalization, where defaulted members may be absent and coercible values may still be in their transport form.
 */
export interface LevelInput {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  level: 1 | 2 | 3 | string;
  role?: "admin" | "user" | null;
}


/**
 * An annotated object
 */
export interface Annotated {
  /**
   * The id
   */
  id: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=18
   */
  n?: number;
}


