//@ts-check
/** Installed public-package qualification. The host injects its dev-only pool. */
import assert from 'node:assert/strict';
import { openStore, readSchema, physicalObjectKey, planPhysicalMigration, migrate, migrationStatus } from '@jarenjs/db';
import { postgresDriver } from '@jarenjs/db/postgres';
import { relational, sql, planTableMigration } from '@jarenjs/db/relational';
import { asyncLive } from '@jarenjs/db/async-live';
import { createDbSearch } from '@jarenjs/db/search';
import { nodeDriver } from '@jarenjs/db/node';
import { bunDriver } from '@jarenjs/db/bun';

/** One installed protocol in both backend directions, using a max-one host pool.
 * @param {any} pool @param {string} schema */
async function qualifyReplication(pool, schema) {
  const model = { $model: '0.1', collections: { notes: { key: '/id', schema: { type: 'object' } } } };
  const driver = postgresDriver(pool, { schema });
  let native, local;
  try {
    await pool.query(`CREATE SCHEMA "${schema}"`);
    native = await openStore(model, { driver, replication: { replica: 'native', retention: 1 },
      capture: { log: true }, jobs: true, live: asyncLive({ pollMs: 60000 }) });
    local = await openStore(model, { driver: typeof Bun === 'undefined' ? nodeDriver() : bunDriver(),
      replication: { replica: 'local' }, capture: { mode: 'journal', log: true } });
    await local.collection('notes').put({ id: 'x/~😀', exact: '9007199254740993', values: [null, true, 0.125] });
    const inbound = (await local.replication.page()).items[0];
    const live = await native.collection('notes').live([{ $for: { it: '$[*]' }, $return: '$it' }]);
    await native.replication.apply(inbound); await live.refresh();
    assert.deepEqual(live.result.rows, [inbound.operations[0].after]);
    const before = await native.changes.page({ after: 0 });
    assert.equal((await native.replication.apply(inbound)).status, 'duplicate');
    assert.deepEqual(await native.changes.page({ after: 0 }), before);
    await native.transaction(async (tx) => {
      await tx.collection('notes').put({ id: 'reply', amount: 7 });
      await tx.jobs.enqueue('receipt', { value: 7 }, { id: 'receipt' });
    });
    assert.ok(await native.jobs.get('receipt'));
    await native.collection('notes').put({ id: 'reply', amount: 8 });
    assert.equal((await native.replication.page()).resetRequired, true);
    const snapshot = await native.replication.snapshot();
    await local.replication.reset(snapshot);
    const mark = await local.changes.page({ after: 0 });
    await local.replication.reset(snapshot);
    assert.deepEqual(await local.changes.page({ after: 0 }), mark);
    for (const receipt of snapshot.receipts) assert.equal((await local.replication.apply(receipt)).status, 'duplicate');
    await native.close(); native = null;
    native = await openStore(model, { driver, replication: { replica: 'native' }, capture: { log: true }, jobs: true });
    assert.equal((await native.replication.apply(inbound)).status, 'duplicate');
    assert.deepEqual(await native.collection('notes').get('reply'), await local.collection('notes').get('reply'));
    assert.equal((await native.jobs.get('receipt')).state, 'pending');
  }
  finally {
    await local?.close(); await native?.close();
    await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
  }
}

/** Exercise exact native adoption and shared transaction ownership.
 * @param {any} pool @param {string} schema */
export async function qualifyPostgres(pool, schema) {
  assert.match(schema, /^jaren_consumer_[a-z0-9_]+$/);
  let store, connection, engine;
  const before = (await pool.query('SHOW search_path')).rows[0].search_path;
  try {
    await pool.query(`CREATE SCHEMA "${schema}"; CREATE TABLE "${schema}".items (
      id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label text NOT NULL,
      amount numeric(30,6) NOT NULL, active boolean NOT NULL, data jsonb NOT NULL, bytes bytea NOT NULL,
      local_stamp timestamp(6) NOT NULL, stamp timestamptz(6) NOT NULL)`);
    const driver = postgresDriver(pool, { schema, windowRows: 1 });
    const codecs = { id: 'integer', label: 'text', amount: 'decimal', active: 'boolean', data: 'json',
      bytes: 'blob-hex', local_stamp: 'local-timestamp', stamp: 'instant' };
    const model = { $model: '0.1', entities: { Item: { schema: { type: 'object', properties: Object.fromEntries(
      Object.keys(codecs).map((name) => [name, name === 'id' ? { type: 'integer', 'x-entity': { key: true, default: 'auto' } } : {}])) },
    physical: { schema, table: 'items', columns: Object.fromEntries(Object.entries(codecs)
      .map(([name, codec]) => [name, { name, codec, null: 'reject' }])) } } } };
    store = await openStore(model, { driver, adopt: true });
    const value = { label: 'a', amount: '9007199254740993.123456', active: false, data: { ok: true }, bytes: '0001ff',
      local_stamp: '2026-09-15T12:34:56.123456', stamp: '2026-09-15T10:34:56.123456Z' };
    const row = await store.entity('Item').create(value);
    assert.deepEqual(row, { id: 1, ...value });
    assert.deepEqual(await store.entity('Item').get(1), row);
    assert.equal((await store.entity('Item').mutate({ op: 'update', key: 1, set: { amount: value.amount, active: false } })).affected, 0);
    await assert.rejects(store.transaction(async (tx) => {
      await tx.entity('Item').update(1, { label: 'withdraw' });
      throw new Error('rollback proof');
    }), /rollback proof/);
    assert.equal((await store.entity('Item').get(1)).label, 'a');
    await store.close(); store = null;
    connection = await driver.open();
    const catalog = await readSchema(connection);
    assert.equal(catalog.catalog.find((object) => object.type === 'table' && object.name === 'items').schema, schema);
    engine = relational(connection);
    assert.equal((await engine.get({ from: 'items', columns: { amount: sql.cast(sql.column('amount'), 'TEXT') } })).amount, value.amount);
    const cursor = engine.iterate({ from: 'items', columns: { id: sql.column('id') } });
    assert.deepEqual((await cursor.next()).value, { id: 1 });
    await engine.dispose(); engine = null;
    assert.equal(connection.metrics().cursors, 0);
    const ddl = 'ALTER TABLE items ADD COLUMN note text';
    let target;
    await assert.rejects(connection.transaction(async (scope) => {
      await scope.exec(ddl);
      target = { dialect: 'postgres', schema, catalog: (await readSchema(scope)).catalog };
      throw new Error('target fixture rollback');
    }), /target fixture rollback/);
    const dispositions = Object.fromEntries(catalog.catalog.map((object) => [physicalObjectKey(object), 'preserve']));
    const tablePlan = await planTableMigration(connection, target, { id: 'items-note', table: 'items', statements: [ddl], dispositions });
    const migration = JSON.parse(JSON.stringify(await planPhysicalMigration(connection, model, model, {
      id: 'items-note', steps: [{ kind: 'table', plan: tablePlan }], dispositions, physicalTarget: target,
      assertions: [{ sql: 'SELECT amount::text AS amount FROM items ORDER BY id', expected: [{ amount: value.amount }] }],
    })));
    assert.deepEqual((await migrate({ connection }, [migration], { baseline: model, shadow: false })).applied, ['items-note']);
    assert.deepEqual((await migrate({ connection }, [migration], { baseline: model, shadow: false })).applied, []);
    assert.equal((await migrationStatus({ connection }, [migration])).upToDate, true);
    await connection.close(); connection = null;
    const managed = { $model: '0.1', collections: { notes: { key: '/id',
      schema: { type: 'object', properties: { id: { type: 'string' }, body: { type: 'string' } } } } },
    entities: { SearchItem: { schema: { type: 'object', properties: {
      id: { type: 'string', 'x-entity': { key: true } }, title: { type: 'string' },
    } } } } };
    let at = 1800000000000;
    const jobs = { now: () => at };
    store = await openStore(managed, { driver, jobs, capture: { mode: 'auto', log: { retention: 2 } } });
    assert.equal(store.capabilities.capture, 'journal');
    assert.equal(store.capabilities.jobs, true);
    await store.transaction(async (tx) => {
      await tx.collection('notes').insert({ id: 'a', body: 'one' });
      await tx.jobs.enqueue('flow', { durable: true }, { id: 'run' });
    });
    await assert.rejects(store.transaction(async (tx) => {
      await tx.collection('notes').insert({ id: 'rolled', body: 'absent' });
      await tx.jobs.enqueue('effect', { id: 'rolled' }, { id: 'rolled' });
      throw new Error('journal rollback');
    }), /journal rollback/);
    assert.equal(await store.jobs.get('rolled'), undefined);
    assert.deepEqual((await store.changes.page({ after: 0 })).items.map((r) => r.seq), [1]);
    await store.collection('notes').put({ id: 'a', body: 'two' });
    await store.collection('notes').put({ id: 'a', body: 'three' });
    assert.equal((await store.changes.page({ after: 0 })).resetRequired, true);
    const old = await store.jobs.claim({ kinds: ['flow'], owner: 'first', leaseMs: 10 });
    await store.jobs.checkpointsFor(old).save('run', 'node', { saved: true });
    await store.close(); store = null;
    at += 11;
    store = await openStore(managed, { driver, jobs, capture: { log: true }, live: asyncLive({ pollMs: 60000 }) });
    assert.deepEqual((await store.changes.page({ after: 1 })).items.map((r) => r.seq), [2, 3]);
    const fresh = await store.jobs.claim({ kinds: ['flow'], owner: 'next' });
    assert.equal(fresh.lease.generation, 2);
    assert.deepEqual(await store.jobs.checkpointsFor(fresh).load('run'), { values: { node: { saved: true } } });
    await assert.rejects(store.jobs.checkpointsFor(old).save('run', 'node', { stale: true }), { code: 'JD2066' });
    await store.jobs.checkpointsFor(fresh).complete('run', { completed: true });
    assert.equal((await store.jobs.get('run')).state, 'done');
    assert.equal(await store.jobs.checkpointsFor(fresh).load('run'), null);
    const query = [{ $for: { it: '$[*]' }, $return: '$it' }];
    const live = await store.collection('notes').live(query);
    assert.deepEqual(store.capabilities.liveModes, ['resnapshot']);
    assert.equal(store.capabilities.dataVersion, false);
    await store.collection('notes').put({ id: 'a', body: 'live' });
    await live.refresh();
    assert.deepEqual(live.result.rows, [{ id: 'a', body: 'live' }]);
    assert.equal(live.stats().pending, 0); await live.close();
    await store.entity('SearchItem').create({ id: 'a', title: 'tea' });
    const search = await createDbSearch(store, 'SearchItem', { version: 1, fields: ['title'] }, { source: 'installed' });
    try {
      assert.equal(search.explain().revision, 'capture'); assert.equal(search.explain().nativeFTS, false);
      assert.deepEqual((await search.search('tea')).hits.map((hit) => hit.id), ['a']);
      await store.entity('SearchItem').update('a', { title: 'coffee' });
      assert.equal((await search.search('tea')).total, 0);
    }
    finally { await search.dispose(); }
    await store.close(); store = null;
    assert.equal(driver.metrics().active, 0);
    assert.equal((await pool.query('SHOW search_path')).rows[0].search_path, before);
    await qualifyReplication(pool, `${schema}_replica`);
    return { exactReadback: true, noOp: true, rollback: true, catalog: true, cursorDisposal: true,
      nativeMigration: true, checkedRepeat: true, journalRollback: true, feedResume: true, sessionRestored: true,
      queueAtomic: true, checkpointResume: true, fencedSettlement: true,
      asyncResnapshot: true, enrolledLexical: true, managedReplication: true,
      replicationBootstrap: true, replicationNoEcho: true };
  }
  finally {
    await engine?.dispose(); await connection?.close(); await store?.close();
    await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`);
  }
}
