// Generated by @jarenjs/contract from the jaren-contract 'shop'.
// Do not edit: regenerate instead.

/**
 * An RFC 3339 string branded for the date operators;
 * structurally identical to the @jarenjs/linq and @jarenjs/db brand.
 */
export type DateTime = string & { __jarenTag: "date-time"; };

export interface CatalogLoadInput {
  since?: DateTime;
  [key: string]: unknown;
}


export interface Product {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  id: number;
  /**
   * Schema constraints this type cannot express: minLength=1
   */
  name: string;
  /**
   * Schema constraints this type cannot express: minimum=0
   */
  price: number;
  tags?: Array<string>;
  [key: string]: unknown;
}


export interface Catalog {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  revision: number;
  products: Array<Product>;
  [key: string]: unknown;
}


export type CatalogLoadOutput = Catalog;

export interface ProductSaveInput {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  id: number;
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  revision: number;
  product: Product;
  [key: string]: unknown;
}


export type ProductSaveOutput = Product;

export interface Conflict {
  current: Product;
  [key: string]: unknown;
}


export type ProductSaveConflictDetails = Conflict;

export interface ImageBytesInput {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  id: number;
  [key: string]: unknown;
}


export type ImageBytesOutput = unknown;

export interface ProductSearchInput {
  q?: string;
  /**
   * Schema constraints this type cannot express: type="integer", minimum=1, maximum=100
   */
  limit?: number;
  tag?: Array<string>;
  flag?: boolean;
  [key: string]: unknown;
}


export type ProductSearchOutput = Array<Product>;

export interface ProductRemoveInput {
  /**
   * Schema constraints this type cannot express: type="integer"
   */
  id: number;
  [key: string]: unknown;
}


export type ProductRemoveOutput = unknown;

/** Every invokable public operation by id: its kind, input and output types, and the error codes it declares. */
export interface Operations {
  'catalog.load': { kind: 'read'; input: CatalogLoadInput; output: CatalogLoadOutput; errors: 'stale' };
  'product.save': { kind: 'command'; input: ProductSaveInput; output: ProductSaveOutput; errors: 'conflict' | 'not-found' };
  'product.search': { kind: 'read'; input: ProductSearchInput; output: ProductSearchOutput; errors: never };
  'product.remove': { kind: 'command'; input: ProductRemoveInput; output: ProductRemoveOutput; errors: 'not-found' };
}

/** Every public operation by id — opaque ones included — with its input type, for `Client.url`. */
export interface UrlOperations {
  'catalog.load': CatalogLoadInput;
  'product.save': ProductSaveInput;
  'image.bytes': ImageBytesInput;
  'product.search': ProductSearchInput;
  'product.remove': ProductRemoveInput;
}

/** The correlation members of every outcome: the caller's attempt id (never read from a response), the server's trace, the contract revision, the entity tag and whether the answer was a 304. A member a binding cannot carry is null (or false for notModified), never omitted. */
export type Meta = { op: string; attempt: unknown; trace: string | null; revision: string | null; etag: string | null; notModified: boolean };

/** The error member of a failed outcome: a declared code, a JC2xxx taxonomy code or a JC205x client code; status is null on a binding without statuses; details is null when none. */
export type WireError = { code: string; message: string; status: number | null; details: unknown; retryable: boolean };

/** What every invoke resolves to — JSON, never a thrown error: a value, or a failure tagged by kind (a declared or taxonomy error, a transport failure, a peer that broke the contract, a local abort). */
export type Outcome<T> = { ok: true; value: T; meta: Meta } | { ok: false; kind: 'failure' | 'network' | 'contract' | 'cancelled'; error: WireError; meta: Meta };

/** Per-call options of invoke. */
export interface InvokeContext { signal?: AbortSignal; attempt?: unknown; idempotencyKey?: string; headers?: Record<string, string>; ifNoneMatch?: string; ifMatch?: string }

/** A contract client over any binding, typed by this contract's operations. */
export interface Client {
  invoke<K extends keyof Operations>(op: K, input: Operations[K]['input'], ctx?: InvokeContext): Promise<Outcome<Operations[K]['output']>>;
  url<K extends keyof UrlOperations>(op: K, input: UrlOperations[K]): string;
  close(): void;
}

/** Every opaque public operation by id, with its input type, for `HttpClient.bytes`. */
export interface ByteOperations {
  'image.bytes': ImageBytesInput;
}

/** Per-call options of bytes: the members of InvokeContext that apply to an opaque call, plus the request body to send — text, bytes, a Web stream, an async iterable of chunks, or none. */
export interface ByteContext { signal?: AbortSignal; attempt?: unknown; headers?: Record<string, string>; ifNoneMatch?: string; ifMatch?: string; body?: string | Uint8Array | ReadableStream<Uint8Array> | AsyncIterable<Uint8Array> | null }

/** The success value of bytes: the status, the response headers (lowercase names), the response media (null when none) and the live response body — a stream the caller reads; null when the response carries none. */
export type ByteResponse = { status: number; headers: Record<string, string>; media: string | null; body: ReadableStream<Uint8Array> | null };

/** The HTTP client: the binding-neutral Client plus bytes over the opaque operations, whose success owns a live stream rather than a JSON value. */
export interface HttpClient extends Client {
  bytes<K extends keyof ByteOperations>(op: K, input: ByteOperations[K], ctx?: ByteContext): Promise<Outcome<ByteResponse>>;
}

/** A declared failure a handler returns (ctx.fail): the declared code, the catalog parameters, the wire details and whether the caller may retry (null defers to the operation's retry policy). */
export type Failure = { code: string; params: Readonly<Record<string, unknown>>; details: unknown; retryable: boolean | null };

/** The binding a handler context comes from. */
export type CarrierName = 'http' | 'port' | 'local';

/** The members every carrier's context shares; `host` is the host lifecycle's acquired value (null by default). */
export interface HandlerContextBase<Host = null> {
  op: unknown;
  trace: string;
  host: Host;
  headers: Readonly<Record<string, string>>;
  signal: AbortSignal | null;
  fail(code: string, params?: Record<string, unknown>, details?: unknown, options?: { retryable?: boolean }): Failure;
}

/** The HTTP binding's context: the request line, the raw body of an opaque operation, the idempotency key, and the entity-tag and status arms. */
export interface HttpHandlerContext<Host = null> extends HandlerContextBase<Host> {
  carrier: 'http';
  method: string;
  path: string;
  params: Readonly<Record<string, string>>;
  body: string | Uint8Array | AsyncIterable<Uint8Array> | null;
  idempotency: Readonly<{ key: string; scope: string }> | null;
  etag(tag: string, options?: { strong?: boolean }): void;
  status(status: number): void;
}

/** The port and local bindings' context: no request line, no body, no key, and no callable etag or status — spelled null, never omitted. */
export interface ChannelHandlerContext<Host = null, Carrier extends 'port' | 'local' = 'port' | 'local'> extends HandlerContextBase<Host> {
  carrier: Carrier;
  method: null;
  path: null;
  params: null;
  body: null;
  idempotency: null;
  etag: null;
  status: null;
}

/** The per-request context a server binding hands a handler, selected by carrier: the HTTP context by default; a carrier union is a discriminated union to narrow on `carrier`. */
export type HandlerContext<Host = null, Carrier extends CarrierName = 'http'> = Extract<HttpHandlerContext<Host> | ChannelHandlerContext<Host, 'port'> | ChannelHandlerContext<Host, 'local'>, { carrier: Carrier }>;

/** The typed handler table of a server binding: one handler per invokable operation, answering the output, a declared failure, or a promise of either. */
export type Handlers<Host = null, Carrier extends CarrierName = 'http'> = { [K in keyof Operations]: (input: Operations[K]['input'], ctx: HandlerContext<Host, Carrier>) => Operations[K]['output'] | Failure | Promise<Operations[K]['output'] | Failure> };
