//@ts-check
/**
 * Focused regressions for the TypeScript printer.
 *
 * The agreement corpus proves the model AGREES with the validator. It cannot
 * prove the printer spells that model correctly, because a corpus entry only
 * ever compiles the output it happens to produce. These cases each pin one
 * spelling rule whose failure mode is source that does not parse, or that
 * parses and means something else.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert';

import { emitTypeScript } from '@jarenjs/emit/typescript';

const emit = (schema, options = {}) =>
  emitTypeScript(schema, { name: 'X', banner: false, ...options }).trim();

describe('the TypeScript printer spells the model correctly', () => {
  it('parenthesizes a union used inside an intersection', () => {
    // `&` binds tighter than `|`, so the bare form is not merely ugly: it is a
    // different, wider type.
    assert.strictEqual(
      emit({ allOf: [{ anyOf: [{ type: 'string' }, { type: 'number' }] },
        { anyOf: [{ type: 'boolean' }, { type: 'null' }] }] }),
      'export type X = (string | number) & (boolean | null);');
  });

  it('quotes a property name TypeScript will not accept bare', () => {
    const out = emit({
      type: 'object',
      properties: { 'my-key': { type: 'string' }, '2fa': { type: 'string' }, ok: { type: 'string' } },
      required: ['my-key'],
      additionalProperties: false,
    });
    assert.match(out, /^ {2}"my-key": string;$/m);
    assert.match(out, /^ {2}"2fa"\?: string;$/m);
    // ...and leaves a legal identifier alone.
    assert.match(out, /^ {2}ok\?: string;$/m);
  });

  it('keeps a comment terminator in a description from closing the block', () => {
    const out = emit({
      type: 'object',
      properties: { a: { type: 'string', description: 'ends with */ oops' } },
      additionalProperties: false,
    });
    // Exactly one comment opens and one closes; the description's terminator
    // must not be the closing one.
    assert.strictEqual(out.match(/\*\//g)?.length, 1);
    assert.match(out, /\*\\\/ oops/);
  });

  it('declares a boolean root instead of emitting nothing', () => {
    assert.strictEqual(emit(true), 'export type X = unknown;');
    assert.strictEqual(emit(false), 'export type X = never;');
  });

  it('reproduces literal JSON data instead of respelling it', () => {
    // The name/doc escaping is a projection of MODEL structure. Applied by key
    // name it also rewrote schema data: a `const` holding a property called
    // `name` came back quoted, and one holding `doc` came back escaped.
    assert.strictEqual(
      emit({ const: { name: 'a-b', doc: ['*/'], other: 1 } }),
      'export type X = {"name":"a-b","doc":["*/"],"other":1};');
    assert.strictEqual(
      emit({ enum: [{ name: 'x-y' }, { name: 'ok' }] }),
      'export type X = {"name":"x-y"} | {"name":"ok"};');
  });

  it('spells optional tuple elements, parenthesized when they need it', () => {
    assert.strictEqual(
      emit({ type: 'array', prefixItems: [{ type: 'string' }], items: false }),
      'export type X = [string?];');
    // The postfix `?` binds to the whole element, so a union inside one is
    // parenthesized first — `[string | number?]` is not that type.
    assert.strictEqual(
      emit({
        type: 'array',
        prefixItems: [{ anyOf: [{ type: 'string' }, { type: 'number' }] }],
        items: false,
      }),
      'export type X = [(string | number)?];');
    // minItems is also a recorded constraint, so the declaration carries a
    // doc comment; the type line is what this case pins.
    assert.match(
      emit({ type: 'array', prefixItems: [{ type: 'string' }], minItems: 1 }),
      /export type X = \[string, \.\.\.Array<unknown>\];/);
  });

  it('never prints a rest with nothing in front of it', () => {
    // The producer collapses the degenerate tuple (EMIT-FORMAT §5), so the
    // spelling `[, ...Array<T>]` cannot occur.
    assert.strictEqual(
      emit({ type: 'array', prefixItems: [], items: { type: 'number' } }),
      'export type X = Array<number>;');
  });

  it('spells a closed empty object as a record of never', () => {
    assert.strictEqual(
      emit({ type: 'object', additionalProperties: false }),
      'export type X = Record<string, never>;');
  });

  it('cannot be made to write code through the source banner', () => {
    // `source` names the input file. A newline in it used to end the line
    // comment and put the remainder into code position.
    const out = emitTypeScript({ type: 'string' },
      { name: 'X', source: 'a.json\nexport const OWNED = 1;' });
    assert.doesNotMatch(out, /^export const OWNED/m);
    assert.match(out, /^\/\/ Generated by @jarenjs\/emit from a\.json export const OWNED = 1;\.$/m);
  });
});
