//@ts-check
/**
 * @file The database-rule oracle: one scenario, run unchanged on every
 * engine. A store's create, update, tracked save and native mutation, and a
 * raw SQL writer beside it, must be refused, audited and left alone alike —
 * on a fresh install and on one upgraded through a migration — and a rule's
 * verdict over a grid of rows must agree with the query engine's.
 */
import assert from 'node:assert/strict';
import { openStore, planInvariants, sqliteDialect, classifyDriverError, planPhysicalMigration, migrate, readSchema, physicalObjectKey } from '@jarenjs/db';
import { nodeDriver } from '@jarenjs/db/node';
import { compileJsonQuery } from '@jarenjs/json/query';

/** @param {string} name @param {string} [codec] @param {string} [nul] */
export const column = (name, codec = 'integer', nul = 'reject') => ({ name, codec, null: nul });

/** Two rules over one table, the first auditing into another. */
export const ruleModel = { $model: '0.1', entities: {
  Entry: { schema: { type: 'object', properties: {
    id: { type: 'integer', 'x-entity': { key: true, default: 'auto' } },
    start: { type: 'integer' }, end: { type: 'integer' }, phase: { type: 'string' },
  } }, physical: { table: 'entry', columns: {
    id: column('id'), start: column('starts'), end: column('ends'), phase: column('phase', 'text'),
  } }, invariants: [
    { name: 'ordered', on: ['insert', 'update'], enforcement: 'database', assert: { $and: [{ $le: ['$.new.start', '$.new.end'] }, { $gt: ['$.new.id', 0] }] },
      audit: { entity: 'Audit', values: { entry: '$.new.id', operation: '$.op' } } },
    { name: 'frozen', on: ['update', 'delete'], enforcement: 'database', assert: { $eq: ['$.old.phase', 'draft'] } },
  ] },
  Audit: { schema: { type: 'object', properties: {
    id: { type: 'integer', 'x-entity': { key: true, default: 'auto' } }, entry: { type: 'integer' }, operation: { type: 'string' },
  } }, physical: { table: 'audit', columns: { id: column('id'), entry: column('entry_id'), operation: column('operation', 'text') } } },
} };

export const RULE_TABLES = {
  sqlite: 'CREATE TABLE entry(id INTEGER PRIMARY KEY, starts INTEGER, ends INTEGER, phase TEXT); CREATE TABLE audit(id INTEGER PRIMARY KEY, entry_id INTEGER, operation TEXT)',
  postgres: 'CREATE TABLE entry(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, starts integer, ends integer, phase text); '
    + 'CREATE TABLE audit(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, entry_id integer, operation text)',
};

/**
 * An engine's fixture: a database holding the given tables, a store driver
 * and a migration target over it, and a raw SQL writer outside the store.
 * An engine that reviews a migration against a complete target catalog
 * supplies `review`: the catalog its steps would leave behind.
 * @typedef {{ dialect: any, driver: any, target: any, exec: (sql: string) => Promise<void>,
 *   all: (sql: string) => Promise<Record<string, any>[]>, source: () => Promise<any[]>,
 *   connection: () => Promise<any>, review?: (steps: any[]) => Promise<any>,
 *   dispose: () => Promise<void> }} RuleFixture
 * @typedef {{ name: string, fixture: (tables: Record<string, string>) => Promise<RuleFixture> }} RuleEngine
 */

/** The SQLite engine: one in-memory database the store and the raw writer share.
 * @returns {RuleEngine} */
export function sqliteEngine() {
  return { name: 'sqlite', async fixture(tables) {
    const connection = await nodeDriver().open(':memory:');
    connection.exec(tables.sqlite);
    let open = true;
    return {
      dialect: sqliteDialect,
      // the store owns the handle it is given: a refused open closes it
      driver: { ...nodeDriver(), open: async () => { open = false; return connection; } },
      target: { driver: { ...nodeDriver(), open: async () => ({ ...connection, close() {} }) } },
      exec: async (sql) => { connection.exec(sql); },
      all: async (sql) => connection.prepare(sql).all([]),
      source: async () => (await readSchema(connection)).objects,
      connection: async () => connection,
      dispose: async () => { if (open) connection.close(); },
    };
  } };
}

/**
 * The scenario. Returns what the tables hold at its end, so two installs and
 * two engines can be compared row for row.
 * @param {RuleEngine} engine @param {boolean} upgraded @returns {Promise<string>}
 */
export async function ruleLifecycle(engine, upgraded) {
  const prepare = async () => {
    const fixture = await engine.fixture(RULE_TABLES);
    if (upgraded) await fixture.exec("INSERT INTO entry VALUES(20, 1, 2, 'draft'); DELETE FROM entry");
    return fixture;
  };
  const refused = await prepare();
  try { await assert.rejects(openStore(ruleModel, { driver: refused.driver }), { code: 'JD0002' }); }
  finally { await refused.dispose(); }
  const fixture = await prepare();
  try {
    const statements = planInvariants(ruleModel, { dialect: fixture.dialect });
    if (upgraded) {
      const from = structuredClone(ruleModel);
      from.entities.Entry.invariants = [];
      const source = await fixture.source();
      const steps = statements.map((statement) => ({ kind: 'ddl', sql: statement.sql }));
      const physicalTarget = await fixture.review?.(steps);
      const migration = await planPhysicalMigration(await fixture.connection(), from, ruleModel, {
        id: 'install-rules', steps, ...(physicalTarget === undefined ? {} : { physicalTarget }),
        dispositions: Object.fromEntries(source.map((object) => [physicalObjectKey(object), 'preserve'])),
        assertions: [{ sql: 'SELECT * FROM entry', expected: [] }],
      });
      // a reviewed target catalog is the whole acceptance where there is one;
      // the model's stored-row walk reads SQLite tables only
      const options = { baseline: from, shadow: false, ...(physicalTarget === undefined ? { model: ruleModel } : {}) };
      await migrate(fixture.target, [migration], options);
      assert.equal((await migrate(fixture.target, [migration], options)).applied.length, 0);
    }
    else for (const statement of statements) await fixture.exec(statement.sql);
    const count = async () => Number((await fixture.all('SELECT count(*) AS n FROM audit'))[0].n);
    const store = await openStore(ruleModel, { driver: fixture.driver, adopt: true });
    try {
      const created = await store.entity('Entry').create({ start: 1, end: 2, phase: 'draft' });
      assert.equal(created.id, 1);
      await assert.rejects(store.entity('Entry').update(1, { start: 3 }), { code: 'JD2096', class: 'constraint' });
      store.entity('Entry').put({ ...created, start: 3 });
      await assert.rejects(store.saveChanges(), { code: 'JD2096', class: 'constraint' });
      store.entity('Entry').discard(1);
      const native = { op: 'update', key: 1, set: { start: 0 } };
      await assert.rejects(store.entity('Entry').mutate({ ...native, set: { start: 3 } }), { code: 'JD2096', class: 'constraint' });
      assert.equal((await store.entity('Entry').mutate(native)).affected, 1);
      const nativeAudit = await count();
      assert.equal((await store.entity('Entry').mutate(native)).affected, 0);
      assert.equal(await count(), nativeAudit);
      for (const sql of ["INSERT INTO entry(starts,ends,phase) VALUES(3,2,'draft')", 'UPDATE entry SET starts=NULL WHERE id=1'])
        await assert.rejects(fixture.exec(sql), (e) => classifyDriverError(e).class === 'constraint');
      await store.entity('Entry').update(1, { phase: 'frozen' });
      const before = await count();
      await store.entity('Entry').update(1, { phase: 'frozen' });
      await fixture.exec("UPDATE entry SET phase='frozen' WHERE id=1");
      assert.equal(await count(), before);
      await assert.rejects(store.entity('Entry').delete(1), { code: 'JD2096' });
      await assert.rejects(fixture.exec('DELETE FROM entry WHERE id=1'), /jaren invariant:frozen/);
      return JSON.stringify({ rows: await fixture.all('SELECT * FROM entry ORDER BY id'), audit: await fixture.all('SELECT * FROM audit ORDER BY id') });
    }
    finally { await store.close(); }
  }
  finally { await fixture.dispose(); }
}

/** Two nullable integers, for the query engine's null truth tables. */
export const truthModel = { $model: '0.1', entities: { Row: { schema: { type: 'object', properties: {
  id: { type: 'integer', 'x-entity': { key: true } }, a: { type: ['integer', 'null'] }, b: { type: ['integer', 'null'] },
} }, physical: { table: 'rows', columns: { id: column('id'), a: column('a', 'integer', 'null'), b: column('b', 'integer', 'null') } } } } };
const TRUTH_TABLES = {
  sqlite: 'CREATE TABLE rows(id INTEGER PRIMARY KEY, a INTEGER, b INTEGER)',
  postgres: 'CREATE TABLE rows(id integer PRIMARY KEY, a bigint, b bigint)',
};
/** A value its codec cannot read: text in an integer column, an integer past the safe range. */
const TRUTH_WRONG_STORAGE = { sqlite: "INSERT INTO rows VALUES(1, 'wrong type', 4)", postgres: 'INSERT INTO rows VALUES(1, 9007199254740993, 4)' };
export const TRUTH_PREDICATES = [{ $eq: ['$.new.a', '$.new.b'] }, { $ne: ['$.new.a', { $const: null }] },
  { $le: ['$.new.a', '$.new.b'] }, { $not: { $lt: ['$.new.a', '$.new.b'] } },
  { $and: [{ $eq: ['$.op', 'insert'] }, { $or: [{ $gt: ['$.new.a', 0] }, { $eq: ['$.new.a', null] }] }] }];

/**
 * Five predicates over `{ null, -1, 2 }²`: the trigger accepts exactly what
 * the query engine accepts, and refuses a row its codec cannot read.
 * @param {RuleEngine} engine @returns {Promise<string>} the verdicts
 */
export async function ruleTruthTable(engine) {
  const verdicts = [];
  for (const expression of TRUTH_PREDICATES) {
    const spec = structuredClone(truthModel);
    spec.entities.Row.invariants = [{ name: 'truth', on: ['insert'], assert: expression, enforcement: 'database' }];
    const evaluate = compileJsonQuery(expression);
    const fixture = await engine.fixture(TRUTH_TABLES);
    try {
      for (const statement of planInvariants(spec, { dialect: fixture.dialect })) await fixture.exec(statement.sql);
      for (const a of [null, -1, 2]) for (const b of [null, -1, 2]) {
        const insert = () => fixture.exec(`INSERT INTO rows VALUES(1, ${a}, ${b})`);
        const accepted = evaluate({ old: null, new: { id: 1, a, b }, op: 'insert' }) === true;
        if (accepted) { await insert(); await fixture.exec('DELETE FROM rows'); }
        else await assert.rejects(insert(), /jaren invariant:truth/);
        verdicts.push(accepted);
      }
      await assert.rejects(fixture.exec(TRUTH_WRONG_STORAGE[engine.name]), /jaren invariant:truth/);
    }
    finally { await fixture.dispose(); }
  }
  return JSON.stringify(verdicts);
}

/** One nullable column per scalar codec. */
const codecs = { i: 'integer', n: 'number', t: 'text', d: 'date', s: 'datetime', f: 'boolean' };
const gridModel = { $model: '0.1', entities: { Row: { schema: { type: 'object', properties: {
  id: { type: 'integer', 'x-entity': { key: true } },
  ...Object.fromEntries(Object.entries(codecs).map(([name, codec]) => [name,
    { type: [codec === 'boolean' ? 'boolean' : ['integer', 'number'].includes(codec) ? codec : 'string', 'null'] }])),
} }, physical: { table: 'rows', columns: { id: column('id'),
  ...Object.fromEntries(Object.entries(codecs).map(([name, codec]) => [name, column(name, codec, 'null')])) } } } } };
const GRID_TABLES = {
  sqlite: 'CREATE TABLE rows(id INTEGER PRIMARY KEY, i INTEGER, n REAL, t TEXT, d TEXT, s TEXT, f INTEGER)',
  postgres: 'CREATE TABLE rows(id integer PRIMARY KEY, i bigint, n double precision, t text, d date, s text, f boolean)',
};
/** Every row an application could store, and rows only a raw writer could. */
const GRID_ROWS = [
  { i: 1, n: 1, t: 'a', d: '2020-01-01', s: '2020-01-01T00:00:00Z', f: true },
  { i: 2, n: 1.5, t: 'B', d: '2019-12-31', s: '2019-12-31T23:59:59Z', f: false },
  { i: -1, n: -0.5, t: 'é', d: '2021-06-15', s: '2021-06-15T12:00:00Z', f: true },
  { i: null, n: null, t: null, d: null, s: null, f: null },
  { i: 3, n: 2.25, t: 'b', d: null, s: '2020-01-01T00:00:00Z', f: null },
  { i: -1, n: -1, t: '', d: '0001-01-01', s: '', f: false },
];
const WRONG_STORAGE = {
  sqlite: ["(1, 'x', 1, 'a', '2020-01-01', 's', 1)", "(1, 1, 'abc', 'a', '2020-01-01', 's', 1)", "(1, 1, 1, 'a', '2020-01-01', 's', 2)",
    "(1, 9007199254740993, 1, 'a', '2020-01-01', 's', 1)"],
  postgres: ["(1, 9007199254740993, 1, 'a', '2020-01-01', 's', TRUE)", "(1, 1, 'NaN', 'a', '2020-01-01', 's', TRUE)",
    "(1, 1, 'Infinity', 'a', '2020-01-01', 's', TRUE)", "(1, 1, 1e300, 'a', '2020-01-01', 's', TRUE)",
    "(1, 1, 1, 'a', '10000-01-01', 's', TRUE)", "(1, 1, 1, 'a', '0001-12-31 BC', 's', TRUE)"],
};
/** Predicates over every codec; the last one reads every column and holds for
 * every well-stored row, so a wrong-storage row is refused by its domain. */
export const GRID_PREDICATES = [
  { $lt: ['$.new.t', 'b'] }, { $ge: ['$.new.d', '2020-01-01'] }, { $eq: ['$.new.f', true] }, { $lt: ['$.new.n', 1.5] },
  { $le: ['$.new.i', '$.new.n'] }, { $eq: ['$.new.i', '$.new.n'] }, { $ne: ['$.new.s', '2020-01-01T00:00:00Z'] },
  { $eq: ['$.new.i', 'x'] }, { $ne: ['$.new.f', 1] }, { $gt: ['$.new.d', '$.new.s'] },
  { $or: [{ $eq: ['$.new.t', null] }, { $gt: ['$.new.t', 'B'] }] }, { $not: { $ge: ['$.new.n', '$.new.i'] } },
  { $and: [{ $ne: ['$.new.i', 'x'] }, { $ne: ['$.new.n', 'x'] }, { $ne: ['$.new.t', 1] }, { $ne: ['$.new.d', 1] }, { $ne: ['$.new.s', 1] }, { $ne: ['$.new.f', 'x'] }] },
];

/** @param {string} engine @param {Record<string, any>} row */
const values = (engine, row) => `(1, ${Object.keys(codecs).map((name) => {
  const value = row[name];
  if (value === null) return 'NULL';
  if (typeof value === 'boolean') return engine === 'sqlite' ? String(Number(value)) : String(value).toUpperCase();
  return typeof value === 'number' ? String(value) : `'${value}'`;
}).join(', ')})`;

/**
 * Every predicate over every row: the trigger accepts exactly what the query
 * engine accepts, and a row whose storage its codec cannot read is refused.
 * Returns the verdicts, for a comparison across engines.
 * @param {RuleEngine} engine @returns {Promise<string>}
 */
export async function ruleGrid(engine) {
  const verdicts = [];
  for (const expression of GRID_PREDICATES) {
    const spec = structuredClone(gridModel);
    spec.entities.Row.invariants = [{ name: 'truth', on: ['insert'], assert: expression, enforcement: 'database' }];
    const evaluate = compileJsonQuery(expression);
    const fixture = await engine.fixture(GRID_TABLES);
    try {
      for (const statement of planInvariants(spec, { dialect: fixture.dialect })) await fixture.exec(statement.sql);
      for (const row of GRID_ROWS) {
        const insert = fixture.exec(`INSERT INTO rows VALUES ${values(engine.name, row)}`);
        const accepted = await insert.then(() => true, (error) => {
          assert.match(String(error?.message), /jaren invariant:truth/);
          return false;
        });
        assert.equal(accepted, evaluate({ old: null, new: { id: 1, ...row }, op: 'insert' }) === true, `${JSON.stringify(expression)} over ${JSON.stringify(row)}`);
        if (accepted) await fixture.exec('DELETE FROM rows');
        verdicts.push(accepted);
      }
      if (expression === GRID_PREDICATES.at(-1)) for (const row of WRONG_STORAGE[engine.name])
        await assert.rejects(fixture.exec(`INSERT INTO rows VALUES ${row}`), /jaren invariant:truth/, row);
    }
    finally { await fixture.dispose(); }
  }
  return JSON.stringify(verdicts);
}

/**
 * The trigger families, declared once: an assignment-sensitive guard, an
 * `UPDATE OF` guard, existence probes of a parent row, and a revision the
 * database moves. The check rules take `enforcement`; the increment is the
 * database's in both.
 * @param {'database' | 'store'} enforcement
 */
export const familyModel = (enforcement) => ({ $model: '0.1', entities: {
  Doc: { schema: { type: 'object', properties: {
    id: { type: 'integer', 'x-entity': { key: true, default: 'auto' } }, status: { type: 'string' }, sealed: { type: ['string', 'null'] },
  } }, physical: { table: 'docs', columns: { id: column('id'), status: column('status', 'text'), sealed: column('sealed', 'text', 'null') } } },
  Line: { schema: { type: 'object', properties: {
    id: { type: 'integer', 'x-entity': { key: true, default: 'auto' } }, doc: { type: 'integer' }, qty: { type: 'integer' },
    note: { type: 'string' }, revision: { type: 'integer' },
  } }, physical: { table: 'lines', columns: { id: column('id'), doc: column('doc_id'), qty: column('qty'), note: column('note', 'text'),
    revision: column('revision') } }, invariants: [
    { name: 'locked', on: ['update'], when: 'assigned', enforcement, assert: { $ne: ['$.old.note', 'locked'] } },
    { name: 'pinned', on: ['update'], columns: ['doc'], enforcement, assert: false },
    { name: 'open_parent', on: ['insert'], enforcement,
      assert: { '$exists-row': { entity: 'Doc', match: { id: '$.new.doc', status: 'draft', sealed: null } } } },
    { name: 'draft_parent', on: ['delete'], enforcement, assert: { $or: [
      { $not: { '$exists-row': { entity: 'Doc', match: { id: '$.old.doc' } } } },
      { '$exists-row': { entity: 'Doc', match: { id: '$.old.doc', status: 'draft' } } }] } },
    { name: 'revision', on: ['update'], enforcement: 'database', assert: true, effects: [{ increment: 'revision' }] },
  ] },
  // a document is the store's alone: its probe runs inside the write's transaction
  Memo: { schema: { type: 'object', properties: { id: { type: 'string', 'x-entity': { key: true } }, parent: { type: 'integer' } } },
    invariants: [{ name: 'memo_parent', on: ['insert'], enforcement: 'store', assert: { '$exists-row': { entity: 'Doc', match: { id: '$.new.parent' } } } }] },
} });
export const FAMILY_TABLES = {
  sqlite: 'CREATE TABLE docs(id INTEGER PRIMARY KEY, status TEXT, sealed TEXT); '
    + 'CREATE TABLE lines(id INTEGER PRIMARY KEY, doc_id INTEGER, qty INTEGER, note TEXT, revision INTEGER)',
  postgres: 'CREATE TABLE docs(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, status text, sealed text); '
    + 'CREATE TABLE lines(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, doc_id integer, qty integer, note text, revision integer)',
};

/** What a write came to: `ok`, or the rule that refused it, whoever enforced it.
 * @param {() => any} write @returns {Promise<string>} */
async function outcome(write) {
  try { await write(); return 'ok'; }
  catch (error) {
    const message = String(/** @type {any} */ (error)?.message);
    const rule = /jaren invariant:(\w+)/.exec(message)?.[1] ?? /persistence invariant '(\w+)'/.exec(message)?.[1];
    if (rule === undefined) throw error;
    return `refused ${rule}`;
  }
}

/**
 * The families' scenario: the store's writes (create, update, a no-op, a
 * tracked save, delete), then — where the database enforces — raw SQL that
 * assigns without changing and sets a revision itself. Returns every outcome
 * and the rows left behind.
 * @param {RuleEngine} engine @param {{ enforcement: 'database' | 'store', upgraded: boolean }} options
 * @returns {Promise<string>}
 */
export async function familyLifecycle(engine, { enforcement, upgraded }) {
  const model = familyModel(enforcement);
  const fixture = await engine.fixture(FAMILY_TABLES);
  try {
    const statements = planInvariants(model, { dialect: fixture.dialect });
    if (upgraded) {
      const from = structuredClone(model);
      from.entities.Line.invariants = [];
      const source = await fixture.source();
      const steps = statements.map((statement) => ({ kind: 'ddl', sql: statement.sql }));
      const physicalTarget = await fixture.review?.(steps);
      const migration = await planPhysicalMigration(await fixture.connection(), from, model, {
        id: 'install-families', steps, ...(physicalTarget === undefined ? {} : { physicalTarget }),
        dispositions: Object.fromEntries(source.map((object) => [physicalObjectKey(object), 'preserve'])), assertions: [],
      });
      await migrate(fixture.target, [migration], { baseline: from, shadow: false, ...(physicalTarget === undefined ? { model } : {}) });
    }
    else for (const statement of statements) await fixture.exec(statement.sql);
    const store = await openStore(model, { driver: fixture.driver });
    try {
      const writes = [], raw = [], rows = [];
      const snapshot = async () => { rows.push(await fixture.all('SELECT * FROM lines ORDER BY id')); };
      const docs = store.entity('Doc'), lines = store.entity('Line');
      await docs.create({ id: 1, status: 'draft', sealed: null });
      await docs.create({ id: 2, status: 'final', sealed: null });
      await docs.create({ id: 3, status: 'draft', sealed: '2020-01-01' });
      // a parent that is a draft, unsealed and present, or no insert. Keys are
      // explicit: a refused insert spends a PostgreSQL identity value, not a rowid
      for (const [id, doc] of [[1, 1], [2, 2], [3, 3], [4, 9], [2, 1]])
        writes.push(await outcome(() => lines.create({ id, doc, qty: 1, note: 'a', revision: 0 })));
      // a no-op writes nothing; the parent column is pinned; a locked line takes no write
      for (const changes of [{ qty: 2 }, { qty: 2 }, { doc: 2 }, { note: 'locked' }, { qty: 3 }])
        writes.push(await outcome(() => lines.update(1, changes)));
      lines.put({ ...(await lines.get(2)), qty: 9 });
      writes.push(await outcome(() => store.saveChanges()));
      lines.put({ ...(await lines.get(2)), doc: 3 });
      writes.push(await outcome(() => store.saveChanges()));
      lines.discard(2);
      await snapshot();
      // a memo names a parent that exists, written directly or tracked
      const memos = store.entity('Memo');
      for (const [id, parent] of [['a', 2], ['b', 9]]) writes.push(await outcome(() => memos.create({ id, parent })));
      for (const [id, parent] of [['c', 9], ['d', 3]]) {
        memos.add({ id, parent });
        writes.push(await outcome(() => store.saveChanges()));
        memos.discard(id);
      }
      // a line leaves a draft parent, or one that is gone; tracked or directly
      lines.remove(2);
      writes.push(await outcome(() => store.saveChanges()));
      await docs.update(1, { status: 'final' });
      writes.push(await outcome(() => lines.delete(1)));
      lines.remove(1);
      writes.push(await outcome(() => store.saveChanges()));
      lines.discard(1);
      await docs.delete(1);
      writes.push(await outcome(() => lines.delete(1)));
      rows.push(await fixture.all('SELECT id, doc_id FROM lines ORDER BY id'));
      if (enforcement === 'database') {
        await fixture.exec("INSERT INTO docs(id, status, sealed) VALUES (4, 'draft', NULL)");
        await fixture.exec("INSERT INTO lines(id, doc_id, qty, note, revision) VALUES (3, 4, 1, 'c', 0)");
        for (const sql of ['UPDATE lines SET qty = qty + 1 WHERE id = 3', 'UPDATE lines SET qty = qty WHERE id = 3',
          'UPDATE lines SET doc_id = doc_id WHERE id = 3', 'UPDATE lines SET qty = qty + 1, revision = 10 WHERE id = 3',
          "UPDATE lines SET note = 'locked' WHERE id = 3", 'UPDATE lines SET qty = qty WHERE id = 3',
          "INSERT INTO lines(doc_id, qty, note, revision) VALUES (9, 1, 'x', 0)"]) {
          raw.push(await outcome(() => fixture.exec(sql)));
          await snapshot();
        }
        raw.push(await outcome(() => fixture.exec('DELETE FROM lines WHERE id = 3')));
      }
      return JSON.stringify({ writes, raw, rows, docs: await fixture.all('SELECT * FROM docs ORDER BY id'),
        lines: await fixture.all('SELECT * FROM lines ORDER BY id') });
    }
    finally { await store.close(); }
  }
  finally { await fixture.dispose(); }
}

/** Declarations the families refuse before anything is planned (JD0005),
 * whichever engine is asked. Each edits `familyModel('database')`. */
export const FAMILY_REFUSALS = [
  ['a probe whose match misses the key', (m) => { m.entities.Line.invariants[2].assert = { '$exists-row': { entity: 'Doc', match: { status: 'draft' } } }; }],
  ['a probe of its own table', (m) => { m.entities.Line.invariants[2].assert = { '$exists-row': { entity: 'Line', match: { id: '$.new.doc' } } }; }],
  ['a probe of an entity without a layout', (m) => {
    m.entities.Note = { schema: { type: 'object', properties: { id: { type: 'integer', 'x-entity': { key: true } } } } };
    m.entities.Line.invariants[2].assert = { '$exists-row': { entity: 'Note', match: { id: '$.new.doc' } } };
  }],
  ['a probe comparing a string with an integer key', (m) => { m.entities.Line.invariants[2].assert = { '$exists-row': { entity: 'Doc', match: { id: 'x' } } }; }],
  ['a probe comparing a text column with an integer key', (m) => { m.entities.Line.invariants[2].assert = { '$exists-row': { entity: 'Doc', match: { id: '$.new.note' } } }; }],
  ['a probe reading the operation', (m) => { m.entities.Line.invariants[2].assert = { '$exists-row': { entity: 'Doc', match: { id: '$.new.doc', status: '$.op' } } }; }],
  ['a malformed probe', (m) => { m.entities.Line.invariants[2].assert = { '$exists-row': { entity: 'Doc' } }; }],
  ['columns that contradict when: changed', (m) => { m.entities.Line.invariants[1].when = 'changed'; }],
  ['columns naming no mapped member', (m) => { m.entities.Line.invariants[1].columns = ['nothing']; }],
  ['columns on an insert-only rule', (m) => { m.entities.Line.invariants[1].on = ['insert']; }],
  ['when on an insert-only rule', (m) => { m.entities.Line.invariants[0].on = ['insert']; }],
  ['an increment the store would enforce', (m) => { m.entities.Line.invariants[4].enforcement = 'store'; }],
  ['an increment beside columns', (m) => { m.entities.Line.invariants[4].columns = ['qty']; }],
  ['an increment of a text member', (m) => { m.entities.Line.invariants[4].effects = [{ increment: 'note' }]; }],
  ['an increment of the key', (m) => { m.entities.Line.invariants[4].effects = [{ increment: 'id' }]; }],
  ['two increments of one member', (m) => { m.entities.Line.invariants.push({ ...m.entities.Line.invariants[4], name: 'again' }); }],
  ['an update rule reading the incremented member', (m) => { m.entities.Line.invariants[0].assert = { $gt: ['$.new.revision', 0] }; }],
  ['an incremented member as a rule column', (m) => { m.entities.Line.invariants[1].columns = ['revision']; }],
];
