//@ts-check
import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { openStore, readSchema, introspectModel } from '@jarenjs/db';
import { postgresDriver, postgresDialect } from '@jarenjs/db/postgres';

it('keeps native inventory metadata and qualified identities in the shared catalog reader', async () => {
  const dialect = postgresDialect({ searchPath: 'tenant' });
  const sql = dialect.introspect.catalog();
  assert.match(sql, /pg_catalog\.pg_policy/);
  assert.match(sql, /pg_catalog\.pg_opclass/);
  const native = { type: 'policy', schema: 'tenant', name: 'scope', owner: 'items', sql: null,
    metadata: JSON.stringify({ command: '*', using: 'tenant = current_setting(\'app.tenant\')' }) };
  const connection = { dialect, prepare: async (text) => ({ all: async () => text === sql ? [native] : [] }) };
  const schema = await readSchema(connection);
  assert.equal(schema.catalog[0].schema, 'tenant');
  assert.equal(schema.catalog[0].metadata.command, '*');
  const result = await introspectModel(connection);
  assert.equal(result.inventory[0].disposition, 'preserve');
});

const url = process.env.JAREN_PG_URL;
describe('PostgreSQL native catalog and host scope', { skip: !url && 'JAREN_PG_URL is not set' }, () => {
  it('inventories definitions, identity, keys, opclasses, constraints, views, functions and RLS without executing a schema change', async () => {
    const { default: pg } = await import('pg');
    const pool = new pg.Pool({ connectionString: url, max: 1 });
    const schema = `jaren_catalog_${process.pid}`;
    let connection;
    try {
      await pool.query(`CREATE SCHEMA "${schema}"`);
      connection = await postgresDriver(pool, { schema }).open();
      await connection.exec(`CREATE TYPE mood AS ENUM ('ready','paused');
        CREATE DOMAIN positive AS numeric CHECK (VALUE > 0);
        CREATE TYPE coordinate AS (x double precision,y double precision);
        CREATE TYPE slots AS RANGE (subtype=integer);
        CREATE TABLE parent (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, label text NOT NULL);
        CREATE TABLE child (id integer PRIMARY KEY, parent_id bigint, label text, state mood,
          CONSTRAINT fk_parent FOREIGN KEY(parent_id) REFERENCES parent(id) ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED);
        ALTER TABLE child ADD CONSTRAINT nonempty CHECK(length(label)>0) NOT VALID;
        CREATE INDEX child_label ON child (label text_pattern_ops DESC) INCLUDE (parent_id) WHERE label IS NOT NULL;
        CREATE VIEW labels WITH (security_barrier=true) AS SELECT id,label FROM child;
        CREATE FUNCTION preserve_body() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog AS $body$
          BEGIN NEW.label := NEW.label || '; -- literal'; RETURN NEW; END $body$;
        CREATE TRIGGER body BEFORE INSERT ON child FOR EACH ROW EXECUTE FUNCTION preserve_body();
        ALTER TABLE child ENABLE ROW LEVEL SECURITY;
        ALTER TABLE child FORCE ROW LEVEL SECURITY;
        CREATE POLICY scoped ON child AS RESTRICTIVE FOR ALL TO PUBLIC USING (label = current_setting('app.scope',true)) WITH CHECK(label <> '')`);
      const before = await readSchema(connection);
      const objects = before.catalog;
      const find = (type, name) => objects.find((object) => object.type === type && object.name === name);
      assert.equal(find('table', 'child').metadata.forceRls, true);
      assert.equal(find('column', 'id').schema, schema);
      assert.equal(objects.find((o) => o.type === 'column' && o.owner === 'parent' && o.name === 'id').metadata.identity, 'd');
      assert.equal(find('constraint', 'fk_parent').metadata.initiallyDeferred, true);
      assert.deepEqual(find('constraint', 'fk_parent').metadata.targetColumns, ['id']);
      assert.equal(find('constraint', 'nonempty').metadata.validated, false);
      assert.equal(find('index', 'child_label').metadata.opclasses[0].name, 'text_pattern_ops');
      assert.equal(find('index', 'child_label').metadata.keyCount, 1);
      assert.match(find('index', 'child_label').sql, /INCLUDE \(parent_id\)/);
      assert.match(find('view', 'labels').sql, /child/);
      assert.match(find('function', 'preserve_body()').sql, /; -- literal/);
      assert.equal(find('trigger', 'body').metadata.functionSchema, schema);
      assert.equal(find('policy', 'scoped').metadata.permissive, false);
      assert.deepEqual(find('policy', 'scoped').metadata.roles, ['public']);
      assert.deepEqual(find('type', 'mood').metadata.enum, ['ready', 'paused']);
      assert.match(find('type', 'positive').metadata.constraints[0].sql, /VALUE > /);
      assert.deepEqual(find('type', 'coordinate').metadata.attributes, [{ name: 'x', type: 'double precision' }, { name: 'y', type: 'double precision' }]);
      assert.equal(find('type', 'slots').metadata.range.subtype, 'integer');
      assert.equal(find('sequence', 'parent_id_seq').metadata.column, 'id');
      const output = await introspectModel(connection);
      assert.equal(output.inventory.find((o) => o.type === 'policy').disposition, 'preserve');
      assert.deepEqual(await readSchema(connection), before);
      const bad = { $model: '0.1', entities: { Child: { schema: { type: 'object', properties: {
        id: { type: 'integer', 'x-entity': { key: true } }, state: { type: 'string' },
      } }, physical: { schema, table: 'child', columns: { id: { name: 'id', codec: 'integer', null: 'reject' },
        state: { name: 'state', codec: 'text', null: 'null' } } } } } };
      // A second connection cannot be borrowed from max:1 while this one is held.
      await connection.close(); connection = null;
      await assert.rejects(openStore(bad, { driver: postgresDriver(pool, { schema }), adopt: true }), /cannot guarantee codec text/);
      const drift = structuredClone(bad); drift.entities.Child.physical.schema = `${schema}_other`;
      await assert.rejects(openStore(drift, { driver: postgresDriver(pool, { schema }), adopt: true }), /driver-owned schema/);
    }
    finally { await connection?.close(); await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); await pool.end(); }
  });

  it('honors an injected non-owner role and tenant scope, and leaves cleanup with the host', async () => {
    const { default: pg } = await import('pg');
    const pool = new pg.Pool({ connectionString: url, max: 1 });
    const schema = `jaren_rls_${process.pid}`, role = `jaren_reader_${process.pid}`;
    let store;
    try {
      await pool.query(`CREATE SCHEMA "${schema}"; CREATE ROLE "${role}" NOLOGIN;
        CREATE TABLE "${schema}".items(id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tenant text NOT NULL, label text NOT NULL DEFAULT 'created');
        INSERT INTO "${schema}".items(tenant) VALUES ('a'),('b');
        CREATE VIEW "${schema}".visible WITH (security_invoker=true) AS SELECT id,tenant,label FROM "${schema}".items;
        ALTER TABLE "${schema}".items ENABLE ROW LEVEL SECURITY;
        CREATE POLICY scoped ON "${schema}".items TO "${role}" USING(tenant=current_setting('app.scope',true)) WITH CHECK(tenant=current_setting('app.scope',true));
        GRANT USAGE ON SCHEMA "${schema}" TO "${role}";
        GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA "${schema}" TO "${role}";
        GRANT USAGE ON ALL SEQUENCES IN SCHEMA "${schema}" TO "${role}"`);
      const model = { $model: '0.1', entities: { Item: { schema: { type: 'object', properties: {
        id: { type: 'integer', 'x-entity': { key: true, default: 'auto' } }, tenant: { type: 'string' }, label: { type: 'string' },
      } }, physical: { schema, table: 'items', columns: { id: { name: 'id', codec: 'integer', null: 'reject', identity: 'by-default' },
        tenant: { name: 'tenant', codec: 'text', null: 'reject' }, label: { name: 'label', codec: 'text', null: 'reject', default: 'database' } } } } } };
      const base = postgresDriver(pool, { schema });
      const driver = { ...base, open: async (...args) => {
        const connection = await base.open(...args);
        await connection.exec(`SET ROLE "${role}"; SET app.scope='a'`);
        return { ...connection, get mustQueue() { return connection.mustQueue; }, close: async () => {
          try { await connection.exec('RESET ROLE; RESET app.scope'); } finally { await connection.close(); }
        } };
      } };
      store = await openStore(model, { driver, adopt: true });
      assert.equal(await store.entity('Item').get(2), undefined);
      assert.equal((await store.entity('Item').get(1)).tenant, 'a');
      assert.deepEqual(await store.entity('Item').create({ tenant: 'a' }), { id: 3, tenant: 'a', label: 'created' });
      await assert.rejects(store.entity('Item').create({ tenant: 'b' }), /row-level security/);
      await store.close(); store = null;
      assert.equal((await pool.query('SELECT current_user=session_user AS restored')).rows[0].restored, true);
      const view = structuredClone(model);
      view.entities.Item.physical.table = 'visible'; view.entities.Item.physical.kind = 'view';
      delete view.entities.Item.physical.columns.id.identity;
      store = await openStore(view, { driver, adopt: true });
      assert.equal(await store.entity('Item').get(2), undefined);
      await assert.rejects(store.entity('Item').create({ tenant: 'a' }), /view/);
    }
    finally {
      await store?.close(); await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE; DROP ROLE IF EXISTS "${role}"`); await pool.end();
    }
  });

  it('preserves exact values with custom parsers and refuses BC, infinity or coerced temporal precision', async () => {
    const { default: pg } = await import('pg');
    const schema = `jaren_codecs_${process.pid}`;
    const forbidden = new Set([1082, 1114, 1184, 17, 2950]);
    const pool = new pg.Pool({ connectionString: url, max: 1, types: { getTypeParser(oid, format) {
      if (forbidden.has(oid)) return () => { throw new Error(`native parser ${oid} must be bypassed`); };
      if ([16, 114, 3802].includes(oid)) return (value) => value;
      if (oid === 1700) return Number;
      return pg.types.getTypeParser(oid, format);
    } } });
    let store, connection;
    try {
      await pool.query(`CREATE SCHEMA "${schema}"; CREATE TABLE "${schema}".items(id uuid PRIMARY KEY,
        amount numeric, active boolean, payload json, day date, local_stamp timestamp(3), stamp timestamptz, bytes bytea)`);
      const codecs = { id: 'uuid', amount: 'decimal', active: 'boolean', payload: 'json', day: 'date', local_stamp: 'local-timestamp', stamp: 'instant', bytes: 'blob-hex' };
      const model = { $model: '0.1', entities: { Item: { schema: { type: 'object', properties: {
        id: { type: 'string', 'x-entity': { key: true } }, ...Object.fromEntries(Object.keys(codecs).filter((k) => k !== 'id').map((key) => [key, {}])),
      } }, physical: { schema, table: 'items', columns: Object.fromEntries(Object.entries(codecs)
        .map(([name, codec]) => [name, { name, codec, null: name === 'id' ? 'reject' : 'null' }])) } } } };
      const driver = postgresDriver(pool, { schema });
      connection = await driver.open();
      assert.deepEqual(await (await connection.prepare('SELECT false AS f, true AS t')).get(), { f: 0, t: 1 });
      await connection.close(); connection = null;
      store = await openStore(model, { driver, adopt: true });
      const row = { id: 'a0000000-0000-0000-0000-000000000001', amount: '9007199254740993.00100', active: false,
        payload: { x: true }, day: '2026-09-15', local_stamp: '2026-09-15T12:34:56.123000', stamp: '2026-09-15T10:34:56.123456Z', bytes: '0001ff' };
      assert.deepEqual(await store.entity('Item').create(row), row);
      await assert.rejects(store.entity('Item').update(row.id, { local_stamp: '2026-09-15T12:34:56.123001' }), { code: 'JD2003' });
      await store.close(); store = null;
      for (const value of ['0001-01-01 BC', 'infinity', '-infinity', '10000-01-01']) {
        await pool.query(`UPDATE "${schema}".items SET day=$1::date`, [value]);
        store = await openStore(model, { driver, adopt: true });
        await assert.rejects(store.entity('Item').get(row.id), { code: 'JD2003' });
        await store.close(); store = null;
      }
    }
    finally { await store?.close(); await connection?.close(); await pool.query(`DROP SCHEMA IF EXISTS "${schema}" CASCADE`); await pool.end(); }
  });
});
