//@ts-check
/**
 * @file The `jaren-contract` command, driven end to end in a temp
 * workspace: each command prints or writes its projection, `--check`
 * exits 0 when current and 1 when drifted (emit's exact closing
 * message), a compile refusal exits 2 printing `code docPath message`,
 * and a usage mistake exits 2 with the usage text.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert';
import { execFileSync, spawnSync } from 'node:child_process';
import * as fs from 'node:fs';
import * as os from 'node:os';
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { load } from './helpers.js';

// A URL pathname (`/C:/repo/...`) is not a native Windows filesystem path:
// handed to execFileSync it resolves against the drive of the cwd and comes
// out as `C:\C:\repo\...`. `fileURLToPath` owns the drive-letter rules.
const CLI = fileURLToPath(new URL('../../packages/contract/src/cli.js', import.meta.url));
const shop = load('./fixtures/shop.contract.json');

/**
 * Run the CLI in a temp dir; answer `{ status, stdout, stderr, files }`.
 * @param {string[]} args
 * @param {(dir: string) => void} [prepare]
 */
function run(args, prepare) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'jaren-contract-'));
  try {
    fs.writeFileSync(path.join(dir, 'shop.json'), JSON.stringify(shop));
    prepare?.(dir);
    const result = spawnSync(process.execPath, [CLI, ...args], { cwd: dir, encoding: 'utf8' });
    return { status: result.status, stdout: result.stdout, stderr: result.stderr, files: snapshot(dir) };
  }
  finally {
    fs.rmSync(dir, { recursive: true, force: true });
  }
}

/** @param {string} dir */
function snapshot(dir) {
  /** @type {Record<string, string>} */
  const out = {};
  for (const file of fs.readdirSync(dir, { recursive: true, encoding: 'utf8' }).sort()) {
    const full = path.join(dir, file);
    if (fs.statSync(full).isFile()) out[file] = fs.readFileSync(full, 'utf8');
  }
  return out;
}

describe('jaren-contract — printing and writing', () => {
  it('describe prints the describe() JSON', () => {
    const r = run(['describe', '--contract', 'shop.json']);
    assert.strictEqual(r.status, 0);
    const description = JSON.parse(r.stdout);
    assert.strictEqual(description.$contract, '0.1');
    assert.strictEqual(description.operations.length, 5);
  });

  it('public prints a contract document; openapi/types/docs write to a directory named by the id', () => {
    const pub = run(['public', '--contract', 'shop.json']);
    assert.strictEqual(pub.status, 0);
    assert.strictEqual(JSON.parse(pub.stdout).$contract, '0.1');
    const r = run(['openapi', '--contract', 'shop.json', '--out', 'api/', '--info-title', 'Shop', '--info-version', '9']);
    assert.strictEqual(r.status, 0);
    assert.match(r.stdout, /wrote api[/\\]shop\.openapi\.json/);
    const doc = JSON.parse(r.files[path.join('api', 'shop.openapi.json')]);
    assert.deepStrictEqual(doc.info, { title: 'Shop', version: '9' });
    const types = run(['types', '--contract', 'shop.json', '--out', 'shop.d.ts']);
    assert.match(types.files['shop.d.ts'], /^\/\/ Generated by @jarenjs\/contract/);
    const docs = run(['docs', '--contract', 'shop.json', '--out', 'out/']);
    assert.match(docs.files[path.join('out', 'shop.md')], /^# shop\n/);
  });
});

describe('jaren-contract — --check exit semantics', () => {
  it('exits 0 when current, 1 when drifted or missing (with emit\'s closing message)', () => {
    const current = run(['openapi', '--contract', 'shop.json', '--out', 'x.json', '--check'],
      (dir) => execFileSync(process.execPath, [CLI, 'openapi', '--contract', 'shop.json', '--out', 'x.json'], { cwd: dir }));
    assert.strictEqual(current.status, 0, current.stderr);
    const missing = run(['openapi', '--contract', 'shop.json', '--out', 'x.json', '--check']);
    assert.strictEqual(missing.status, 1);
    assert.match(missing.stderr, /missing: x\.json/);
    assert.match(missing.stderr, /Generated output is out of date\. Run jaren-contract without --check\./);
    const drifted = run(['openapi', '--contract', 'shop.json', '--out', 'x.json', '--check'],
      (dir) => fs.writeFileSync(path.join(dir, 'x.json'), '{"stale":true}'));
    assert.strictEqual(drifted.status, 1);
    assert.match(drifted.stderr, /out of date: x\.json/);
    assert.deepStrictEqual(drifted.files['x.json'], '{"stale":true}', '--check never writes');
  });
});

describe('jaren-contract — failure exits', () => {
  it('exits 2 on a compile refusal, printing code docPath message', () => {
    const r = run(['types', '--contract', 'bad.json'],
      (dir) => fs.writeFileSync(path.join(dir, 'bad.json'), JSON.stringify({ $contract: '0.1', operations: { a: { kind: 'read' } } })));
    assert.strictEqual(r.status, 2);
    assert.match(r.stderr, /JC0006 \/operations\/a\/output output is required/);
  });

  it('exits 2 on an unreadable document, an unknown command, a missing --contract, and --check without --out', () => {
    const unreadable = run(['describe', '--contract', 'nope.json']);
    assert.strictEqual(unreadable.status, 2);
    assert.match(unreadable.stderr, /cannot read contract 'nope\.json'/);
    const unknown = run(['nope', '--contract', 'shop.json']);
    assert.strictEqual(unknown.status, 2);
    assert.match(unknown.stderr, /unknown command 'nope'/);
    assert.match(unknown.stderr, /Usage:/);
    const noContract = run(['describe']);
    assert.strictEqual(noContract.status, 2);
    const checkless = run(['openapi', '--contract', 'shop.json', '--check']);
    assert.strictEqual(checkless.status, 2);
    assert.match(checkless.stderr, /--check needs --out/);
  });

  it('reports dropped keywords on stderr under openapi --lenient and refuses without it', () => {
    const doc = {
      $contract: '0.1',
      operations: { a: { kind: 'read', input: { type: 'object', properties: { m: { type: 'string', required: true } } }, output: true, http: { method: 'GET', path: '/a' } } },
    };
    const strict = run(['openapi', '--contract', 'lenient.json'],
      (dir) => fs.writeFileSync(path.join(dir, 'lenient.json'), JSON.stringify(doc)));
    assert.strictEqual(strict.status, 2);
    assert.match(strict.stderr, /JC0060/);
    const lenient = run(['openapi', '--contract', 'lenient.json', '--lenient'],
      (dir) => fs.writeFileSync(path.join(dir, 'lenient.json'), JSON.stringify(doc)));
    assert.strictEqual(lenient.status, 0);
    assert.match(lenient.stderr, /dropped required at \/operations\/a\/input\/properties\/m\/required/);
  });
});

describe('jaren-contract diff — the compatibility gate', () => {
  /** @param {(v2: any) => void} edit */
  const withV2 = (edit) => (/** @type {string} */ dir) => {
    const v2 = JSON.parse(JSON.stringify(shop));
    edit(v2);
    fs.writeFileSync(path.join(dir, 'shop-v2.json'), JSON.stringify(v2));
  };

  it('prints the classified diff and exits 0 without --fail-on, even on a breaking change', () => {
    const r = run(['diff', '--from', 'shop.json', '--to', 'shop-v2.json'],
      withV2((v2) => { delete v2.operations['product.remove']; }));
    assert.strictEqual(r.status, 0);
    const diff = JSON.parse(r.stdout);
    assert.deepStrictEqual(diff.breaking.map((/** @type {any} */ c) => [c.rule, c.op]), [['R1', 'product.remove']]);
    assert.deepStrictEqual([diff.additive, diff.neutral, diff.unknown], [[], [], []]);
  });

  it('--fail-on breaking exits 1 exactly when the class is present, naming the count on stderr', () => {
    const broken = run(['diff', '--from', 'shop.json', '--to', 'shop-v2.json', '--fail-on', 'breaking'],
      withV2((v2) => { delete v2.operations['product.remove']; }));
    assert.strictEqual(broken.status, 1);
    assert.match(broken.stderr, /1 breaking change/);

    const additive = run(['diff', '--from', 'shop.json', '--to', 'shop-v2.json', '--fail-on', 'breaking'],
      withV2((v2) => { v2.operations['product.save'].errors['too-many'] = { status: 429 }; }));
    assert.strictEqual(additive.status, 0, 'an additive change passes a breaking-only gate');

    const strict = run(['diff', '--from', 'shop.json', '--to', 'shop-v2.json', '--fail-on', 'breaking,additive'],
      withV2((v2) => { v2.operations['product.save'].errors['too-many'] = { status: 429 }; }));
    assert.strictEqual(strict.status, 1);
  });

  it('usage and compile refusals exit 2: missing --to, an unknown class, a document that does not compile', () => {
    const missing = run(['diff', '--from', 'shop.json']);
    assert.strictEqual(missing.status, 2);
    assert.match(missing.stderr, /--from <file> and --to <file>/);

    const badClass = run(['diff', '--from', 'shop.json', '--to', 'shop.json', '--fail-on', 'bad'],
      withV2(() => {}));
    assert.strictEqual(badClass.status, 2);
    assert.match(badClass.stderr, /not a change class/);

    const refused = run(['diff', '--from', 'shop.json', '--to', 'shop-v2.json'],
      withV2((v2) => { v2.operations['product.save'].kind = 'write'; }));
    assert.strictEqual(refused.status, 2);
    assert.match(refused.stderr, /JC0004/);
  });
});

describe('jaren-contract — module documents (the shared @jarenjs/json/node loader)', () => {
  const PEN = pathToFileURL(fileURLToPath(new URL('../../packages/linq/src/contract/index.js', import.meta.url))).href;
  /** The shop contract as a module: a default export, a named export, a pen builder. */
  const modules = (/** @type {string} */ dir) => {
    fs.writeFileSync(path.join(dir, 'default.mjs'), `export default ${JSON.stringify(shop)};\n`);
    fs.writeFileSync(path.join(dir, 'named.mjs'), `export const contract = ${JSON.stringify(shop)};\n`);
    fs.writeFileSync(path.join(dir, 'pen.mjs'), [
      `import { defineContract, read, command, error, http } from '${PEN}';`,
      "export const contract = defineContract({ id: 'pen' }, {",
      "  'catalog.load': read({ input: { type: 'object', properties: { since: { type: 'string' } } }, output: { type: 'object', required: ['revision'], properties: { revision: { type: 'integer' } } }, http: http({ method: 'GET', path: '/api/catalog' }) }),",
      "  'product.save': command({ input: { type: 'object', required: ['id'], properties: { id: { type: 'integer' } } }, output: { type: 'object' }, errors: { conflict: error({ status: 409 }) }, http: http({ method: 'PUT', path: '/api/products/{id}' }) }),",
      '});',
      '',
    ].join('\n'));
    fs.writeFileSync(path.join(dir, 'impure.mjs'), `export default { ...${JSON.stringify(shop)}, id: 'shop-' + Date.now() + Math.random() };\n`);
    fs.writeFileSync(path.join(dir, 'nodoc.mjs'), 'export default 42;\n');
    fs.writeFileSync(path.join(dir, 'shop.txt'), JSON.stringify(shop));
    fs.writeFileSync(path.join(dir, 'typed.ts'), `const contract: unknown = ${JSON.stringify(shop)};\nexport default contract;\n`);
  };

  it('every command reads a module: default export, named `contract` export, and a real linq contract pen', () => {
    for (const file of ['default.mjs', 'named.mjs']) {
      const described = run(['describe', '--contract', file], modules);
      assert.strictEqual(described.status, 0, described.stderr);
      assert.strictEqual(JSON.parse(described.stdout).operations.length, 5, file);
      const pub = run(['public', '--contract', file], modules);
      assert.strictEqual(JSON.parse(pub.stdout).$contract, '0.1');
    }
    const pen = run(['types', '--contract', 'pen.mjs', '--out', 'pen.d.ts'], modules);
    assert.strictEqual(pen.status, 0, pen.stderr);
    assert.match(pen.files['pen.d.ts'], /'catalog.load'/);
    assert.match(pen.files['pen.d.ts'], /'product.save'/);
    const docs = run(['docs', '--contract', 'pen.mjs', '--out', 'out/'], modules);
    assert.match(docs.files[path.join('out', 'pen.md')], /^# pen\n/);
    const openapi = run(['openapi', '--contract', 'pen.mjs'], modules);
    assert.strictEqual(openapi.status, 0, openapi.stderr);
    assert.strictEqual(JSON.parse(openapi.stdout).openapi.startsWith('3.'), true);
  });

  it('an impure module, a non-document export, an unknown extension and a .ts where types are not stripped exit 2 under the jaren-contract: prefix', () => {
    const impure = run(['describe', '--contract', 'impure.mjs'], modules);
    assert.strictEqual(impure.status, 2);
    assert.match(impure.stderr, /^jaren-contract: the contract module 'impure\.mjs' is not pure — two loads emitted different documents; no clock, no env, no randomness in a contract module/m);
    const nodoc = run(['describe', '--contract', 'nodoc.mjs'], modules);
    assert.strictEqual(nodoc.status, 2);
    assert.match(nodoc.stderr, /jaren-contract: module 'nodoc\.mjs' exports neither a default nor a 'contract' document/);
    const ext = run(['describe', '--contract', 'shop.txt'], modules);
    assert.strictEqual(ext.status, 2);
    assert.match(ext.stderr, /jaren-contract: cannot read contract 'shop\.txt': neither a \.json file nor a module/);
    const stripped = run(['describe', '--contract', 'typed.ts'], modules);
    assert.strictEqual(stripped.status, 0, stripped.stderr);
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'jaren-contract-ts-'));
    try {
      modules(dir);
      const refused = spawnSync(process.execPath, ['--no-warnings=ExperimentalWarning', '--no-strip-types', CLI, 'describe', '--contract', 'typed.ts'], { cwd: dir, encoding: 'utf8' });
      assert.strictEqual(refused.status, 2);
      assert.match(refused.stderr, /cannot load contract module 'typed\.ts': .* — a \.ts module loads only where Node strips types/);
    }
    finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('types --out … --check against the module is the types twin: missing 1, generated 0, current 0, a changed module 1; two ordinary runs are identical and claim nothing', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'jaren-contract-check-'));
    const cli = (/** @type {string[]} */ args) => spawnSync(process.execPath, [CLI, ...args], { cwd: dir, encoding: 'utf8' });
    try {
      modules(dir);
      const missing = cli(['types', '--contract', 'pen.mjs', '--out', 'pen.d.ts', '--check']);
      assert.strictEqual(missing.status, 1);
      assert.match(missing.stderr, /missing: pen\.d\.ts/);
      const generated = cli(['types', '--contract', 'pen.mjs', '--out', 'pen.d.ts']);
      assert.strictEqual(generated.status, 0, generated.stderr);
      assert.match(generated.stdout, /wrote pen\.d\.ts/);
      const before = fs.statSync(path.join(dir, 'pen.d.ts')).mtimeMs;
      const text = fs.readFileSync(path.join(dir, 'pen.d.ts'), 'utf8');
      const current = cli(['types', '--contract', 'pen.mjs', '--out', 'pen.d.ts', '--check']);
      assert.strictEqual(current.status, 0, current.stderr);
      const again = cli(['types', '--contract', 'pen.mjs', '--out', 'pen.d.ts']);
      assert.strictEqual(again.status, 0, again.stderr);
      assert.strictEqual(again.stdout, '', 'an unchanged output is not claimed as written');
      assert.strictEqual(fs.statSync(path.join(dir, 'pen.d.ts')).mtimeMs, before, 'an unchanged output is not rewritten');
      assert.strictEqual(fs.readFileSync(path.join(dir, 'pen.d.ts'), 'utf8'), text);
      // the module moves: the committed declaration is stale
      const source = fs.readFileSync(path.join(dir, 'pen.mjs'), 'utf8');
      fs.writeFileSync(path.join(dir, 'pen.mjs'), source.replace("'catalog.load'", "'catalog.reload'"));
      const drifted = cli(['types', '--contract', 'pen.mjs', '--out', 'pen.d.ts', '--check']);
      assert.strictEqual(drifted.status, 1);
      assert.match(drifted.stderr, /out of date: pen\.d\.ts/);
      assert.strictEqual(fs.readFileSync(path.join(dir, 'pen.d.ts'), 'utf8'), text, '--check never writes');
    }
    finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('diff loads both endpoints independently — a module on either side — and names the flag of the one that failed', () => {
    const ok = run(['diff', '--from', 'shop.json', '--to', 'named.mjs'], modules);
    assert.strictEqual(ok.status, 0, ok.stderr);
    const both = run(['diff', '--from', 'default.mjs', '--to', 'pen.mjs', '--fail-on', 'breaking'], modules);
    assert.strictEqual(both.status, 1, 'the pen drops operations: breaking');
    const badFrom = run(['diff', '--from', 'impure.mjs', '--to', 'shop.json'], modules);
    assert.strictEqual(badFrom.status, 2);
    assert.match(badFrom.stderr, /the --from module 'impure\.mjs' is not pure/);
    const badTo = run(['diff', '--from', 'shop.json', '--to', 'nope.mjs'], modules);
    assert.strictEqual(badTo.status, 2);
    assert.match(badTo.stderr, /cannot load --to module 'nope\.mjs'/);
  });
});
