//@ts-check
/**
 * @file `toTypeScript`: the declarations equal the golden (which
 * `test/consumer/types.ts` compiles under `npm run test:types` beside a
 * consumer snippet that calls `invoke('product.save', …)` and reads a
 * typed outcome — TypeScript is the judge of a TypeScript question, the
 * emit pattern), render byte-identical twice, name the operation types
 * predictably (and uniquely under collisions), and spell the fixed D6
 * shapes exactly as the runtime member lists have them.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert';
import { readFileSync } from 'node:fs';

import { compileContract, ContractHostError } from '@jarenjs/contract';
import { OUTCOME_META_MEMBERS, OUTCOME_ERROR_MEMBERS } from '@jarenjs/contract/client';
import { toTypeScript } from '@jarenjs/contract/project';

import { load } from './helpers.js';

const shop = load('./fixtures/shop.contract.json');
const GOLDEN = new URL('./fixtures/shop.d.ts', import.meta.url);

describe('toTypeScript — the golden and determinism', () => {
  it('equals the golden (regenerate with: node packages/contract/src/cli.js types --contract test/contract/fixtures/shop.contract.json --out test/contract/fixtures/shop.d.ts) and renders byte-identical twice', () => {
    const contract = compileContract(shop);
    const first = toTypeScript(contract);
    assert.strictEqual(first, readFileSync(GOLDEN, 'utf8'),
      'test/contract/fixtures/shop.d.ts is stale — regenerate it (the consumer snippet in test/consumer/types.ts compiles against it)');
    assert.strictEqual(toTypeScript(contract), first);
  });

  it('starts with the banner unless turned off', () => {
    const contract = compileContract(shop);
    assert.ok(toTypeScript(contract).startsWith("// Generated by @jarenjs/contract from the jaren-contract 'shop'.\n// Do not edit: regenerate instead.\n\n"));
    assert.ok(toTypeScript(contract, { banner: false }).startsWith('export interface CatalogLoadInput {'));
    assert.throws(() => toTypeScript(contract, /** @type {any} */ ({ banner: 'yes' })), (/** @type {any} */ e) => e instanceof ContractHostError && e.code === 'JC1008');
    assert.throws(() => toTypeScript(/** @type {any} */ (shop)), (/** @type {any} */ e) => e.code === 'JC1008');
  });
});

describe('toTypeScript — what it declares', () => {
  const out = toTypeScript(compileContract(shop), { banner: false });

  it('declares the operation types by PascalCase id, the $defs by name, and the maps', () => {
    for (const name of ['CatalogLoadInput', 'CatalogLoadOutput', 'ProductSaveInput', 'ProductSaveOutput', 'ProductSaveConflictDetails',
      'ImageBytesInput', 'ImageBytesOutput', 'ProductSearchInput', 'ProductSearchOutput', 'ProductRemoveInput', 'ProductRemoveOutput',
      'Product', 'Catalog', 'Conflict']) {
      assert.match(out, new RegExp(`^export (interface|type) ${name}\\b`, 'm'), name);
    }
    assert.match(out, /^export type CatalogLoadOutput = Catalog;$/m);
    assert.match(out, /^export type ProductSaveConflictDetails = Conflict;$/m);
    assert.match(out, /^export type ImageBytesOutput = unknown;$/m);
    assert.doesNotMatch(out, /^export type Contract\b/m, 'the synthetic root is not declared');
    assert.match(out, /^export interface Operations \{\n {2}'catalog\.load': \{ kind: 'read'; input: CatalogLoadInput; output: CatalogLoadOutput; errors: 'stale' \};\n {2}'product\.save': \{ kind: 'command'; input: ProductSaveInput; output: ProductSaveOutput; errors: 'conflict' \| 'not-found' \};\n {2}'product\.search': \{ kind: 'read'; input: ProductSearchInput; output: ProductSearchOutput; errors: never \};\n {2}'product\.remove': \{ kind: 'command'; input: ProductRemoveInput; output: ProductRemoveOutput; errors: 'not-found' \};\n\}/m);
    assert.match(out, /^export interface UrlOperations \{\n(?: {2}'[a-z.]+': [A-Za-z]+;\n){5}\}/m, 'every public operation, the opaque one included');
    assert.match(out, /'image\.bytes': ImageBytesInput;/);
    assert.doesNotMatch(out, /'image\.bytes': \{ kind/, 'an opaque operation is not invokable');
  });

  it('spells Meta and WireError exactly as the runtime member lists have them, and the rest of the fixed text', () => {
    const meta = /^export type Meta = \{ (.*) \};$/m.exec(out);
    assert.ok(meta !== null);
    assert.deepStrictEqual(meta[1].split('; ').map((m) => m.split(':')[0]), [...OUTCOME_META_MEMBERS]);
    assert.strictEqual(meta[1], 'op: string; attempt: unknown; trace: string | null; revision: string | null; etag: string | null; notModified: boolean');
    const error = /^export type WireError = \{ (.*) \};$/m.exec(out);
    assert.ok(error !== null);
    assert.deepStrictEqual(error[1].split('; ').map((m) => m.split(':')[0]), [...OUTCOME_ERROR_MEMBERS]);
    assert.strictEqual(error[1], 'code: string; message: string; status: number | null; details: unknown; retryable: boolean');
    assert.match(out, /^export type Outcome<T> = \{ ok: true; value: T; meta: Meta \} \| \{ ok: false; kind: 'failure' \| 'network' \| 'contract' \| 'cancelled'; error: WireError; meta: Meta \};$/m);
    assert.match(out, /^export interface InvokeContext \{ signal\?: AbortSignal; attempt\?: unknown; idempotencyKey\?: string; headers\?: Record<string, string>; ifNoneMatch\?: string; ifMatch\?: string \}$/m);
    assert.match(out, /invoke<K extends keyof Operations>\(op: K, input: Operations\[K\]\['input'\], ctx\?: InvokeContext\): Promise<Outcome<Operations\[K\]\['output'\]>>;/);
    assert.match(out, /url<K extends keyof UrlOperations>\(op: K, input: UrlOperations\[K\]\): string;/);
    assert.match(out, /^export type Handlers = \{ \[K in keyof Operations\]: \(input: Operations\[K\]\['input'\], ctx: HandlerContext\) => Operations\[K\]\['output'\] \| Failure \| Promise<Operations\[K\]\['output'\] \| Failure> \};$/m);
    assert.match(out, /^export interface HandlerContext \{$/m);
  });

  it('types an input-less operation as null, keeps names unique under collisions, and leaves server operations out', () => {
    const contract = compileContract({
      $contract: '0.1',
      // ThingPutInput is REACHABLE (thing.get's output references it), so
      // the operation type of thing.put must step aside; an UNREACHABLE
      // def never enters the projection and never takes a name
      $defs: { ThingPutInput: { type: 'string' }, Unreachable: { type: 'boolean' }, Shared: { type: 'object', properties: { n: { type: 'integer' } } } },
      operations: {
        'thing.get': { kind: 'read', output: { $ref: '#/$defs/ThingPutInput' }, http: { method: 'GET', path: '/t' } },
        'thing.put': { kind: 'command', input: { type: 'object', properties: { x: { $ref: '#/$defs/Shared' } } }, output: { $ref: '#/$defs/Shared' } },
        'no.input': { kind: 'read', output: { type: 'object' }, http: { method: 'GET', path: '/n' } },
        'only.server': { kind: 'read', output: true, policy: { audience: 'server' }, http: { method: 'GET', path: '/s' } },
      },
    });
    const ts = toTypeScript(contract, { banner: false });
    assert.match(ts, /^export type ThingPutInput = string;$/m, 'the contract\'s own reachable def keeps its name');
    assert.match(ts, /'thing\.put': \{ kind: 'command'; input: ThingPutInput2; output: ThingPutOutput; errors: never \};/);
    assert.match(ts, /^export interface ThingPutInput2 \{/m);
    assert.match(ts, /^export type ThingPutOutput = Shared;$/m);
    assert.match(ts, /'thing\.get': \{ kind: 'read'; input: null; output: ThingGetOutput; errors: never \};/);
    assert.match(ts, /^export type ThingGetOutput = ThingPutInput;$/m);
    assert.match(ts, /'no\.input': \{ kind: 'read'; input: null; output: NoInputOutput; errors: never \};/);
    assert.match(ts, /^ {2}'no\.input': null;$/m);
    assert.doesNotMatch(ts, /only\.server|OnlyServer|Unreachable/);
    assert.strictEqual((ts.match(/^export interface Shared \{/gm) ?? []).length, 1, 'a shared $defs entry is declared once');
  });
});
