//@ts-check
/**
 * @file `toTypeScript`: the declarations equal the golden (which
 * `test/consumer/types.ts` compiles under `npm run test:types` beside a
 * consumer snippet that calls `invoke('product.save', …)` and reads a
 * typed outcome — TypeScript is the judge of a TypeScript question, the
 * emit pattern), render byte-identical twice, name the operation types
 * predictably (and uniquely under collisions), spell the fixed D6
 * shapes exactly as the runtime member lists have them, and carry the
 * suite's `DateTime` brand on every date-formatted string.
 */

import { describe, it } from 'node:test';
import assert from 'node:assert';
import { readFileSync } from 'node:fs';

import { compileContract, ContractHostError } from '@jarenjs/contract';
import { OUTCOME_META_MEMBERS, OUTCOME_ERROR_MEMBERS } from '@jarenjs/contract/client';
import { toTypeScript } from '@jarenjs/contract/project';

import { load } from './helpers.js';

const shop = load('./fixtures/shop.contract.json');
const GOLDEN = new URL('./fixtures/shop.d.ts', import.meta.url);

describe('toTypeScript — the golden and determinism', () => {
  it('equals the golden (regenerate with: node packages/contract/src/cli.js types --contract test/contract/fixtures/shop.contract.json --out test/contract/fixtures/shop.d.ts) and renders byte-identical twice', () => {
    const contract = compileContract(shop);
    const first = toTypeScript(contract);
    assert.strictEqual(first, readFileSync(GOLDEN, 'utf8'),
      'test/contract/fixtures/shop.d.ts is stale — regenerate it (the consumer snippet in test/consumer/types.ts compiles against it)');
    assert.strictEqual(toTypeScript(contract), first);
  });

  it('starts with the banner unless turned off', () => {
    const contract = compileContract(shop);
    const banner = "// Generated by @jarenjs/contract from the jaren-contract 'shop'.\n// Do not edit: regenerate instead.\n\n";
    assert.ok(toTypeScript(contract).startsWith(banner));
    // banner: false removes exactly the banner, whatever declaration leads
    assert.strictEqual(toTypeScript(contract, { banner: false }), toTypeScript(contract).slice(banner.length));
    assert.throws(() => toTypeScript(contract, /** @type {any} */ ({ banner: 'yes' })), (/** @type {any} */ e) => e instanceof ContractHostError && e.code === 'JC1008');
    assert.throws(() => toTypeScript(/** @type {any} */ (shop)), (/** @type {any} */ e) => e.code === 'JC1008');
  });
});

describe('toTypeScript — what it declares', () => {
  const out = toTypeScript(compileContract(shop), { banner: false });

  it('declares the operation types by PascalCase id, the $defs by name, and the maps', () => {
    for (const name of ['CatalogLoadInput', 'CatalogLoadOutput', 'ProductSaveInput', 'ProductSaveOutput', 'ProductSaveConflictDetails',
      'ImageBytesInput', 'ImageBytesOutput', 'ProductSearchInput', 'ProductSearchOutput', 'ProductRemoveInput', 'ProductRemoveOutput',
      'Product', 'Catalog', 'Conflict']) {
      assert.match(out, new RegExp(`^export (interface|type) ${name}\\b`, 'm'), name);
    }
    assert.match(out, /^export type CatalogLoadOutput = Catalog;$/m);
    assert.match(out, /^export type ProductSaveConflictDetails = Conflict;$/m);
    assert.match(out, /^export type ImageBytesOutput = unknown;$/m);
    assert.doesNotMatch(out, /^export type Contract\b/m, 'the synthetic root is not declared');
    assert.match(out, /^export interface Operations \{\n {2}'catalog\.load': \{ kind: 'read'; input: CatalogLoadInput; output: CatalogLoadOutput; errors: 'stale' \};\n {2}'product\.save': \{ kind: 'command'; input: ProductSaveInput; output: ProductSaveOutput; errors: 'conflict' \| 'not-found' \};\n {2}'product\.search': \{ kind: 'read'; input: ProductSearchInput; output: ProductSearchOutput; errors: never \};\n {2}'product\.remove': \{ kind: 'command'; input: ProductRemoveInput; output: ProductRemoveOutput; errors: 'not-found' \};\n\}/m);
    assert.match(out, /^export interface UrlOperations \{\n(?: {2}'[a-z.]+': [A-Za-z]+;\n){5}\}/m, 'every public operation, the opaque one included');
    assert.match(out, /'image\.bytes': ImageBytesInput;/);
    assert.doesNotMatch(out, /'image\.bytes': \{ kind/, 'an opaque operation is not invokable');
  });

  it('spells Meta and WireError exactly as the runtime member lists have them, and the rest of the fixed text', () => {
    const meta = /^export type Meta = \{ (.*) \};$/m.exec(out);
    assert.ok(meta !== null);
    assert.deepStrictEqual(meta[1].split('; ').map((m) => m.split(':')[0]), [...OUTCOME_META_MEMBERS]);
    assert.strictEqual(meta[1], 'op: string; attempt: unknown; trace: string | null; revision: string | null; etag: string | null; notModified: boolean');
    const error = /^export type WireError = \{ (.*) \};$/m.exec(out);
    assert.ok(error !== null);
    assert.deepStrictEqual(error[1].split('; ').map((m) => m.split(':')[0]), [...OUTCOME_ERROR_MEMBERS]);
    assert.strictEqual(error[1], 'code: string; message: string; status: number | null; details: unknown; retryable: boolean');
    assert.match(out, /^export type Outcome<T> = \{ ok: true; value: T; meta: Meta \} \| \{ ok: false; kind: 'failure' \| 'network' \| 'contract' \| 'cancelled'; error: WireError; meta: Meta \};$/m);
    assert.match(out, /^export interface InvokeContext \{ signal\?: AbortSignal; attempt\?: unknown; idempotencyKey\?: string; headers\?: Record<string, string>; ifNoneMatch\?: string; ifMatch\?: string \}$/m);
    assert.match(out, /invoke<K extends keyof Operations>\(op: K, input: Operations\[K\]\['input'\], ctx\?: InvokeContext\): Promise<Outcome<Operations\[K\]\['output'\]>>;/);
    assert.match(out, /url<K extends keyof UrlOperations>\(op: K, input: UrlOperations\[K\]\): string;/);
    assert.match(out, /^export type Handlers<Host = null, Carrier extends CarrierName = 'http'> = \{ \[K in keyof Operations\]: \(input: Operations\[K\]\['input'\], ctx: HandlerContext<Host, Carrier>\) => Operations\[K\]\['output'\] \| Failure \| Promise<Operations\[K\]\['output'\] \| Failure> \};$/m);
    assert.match(out, /^export type CarrierName = 'http' \| 'port' \| 'local';$/m);
    assert.match(out, /^export interface HttpHandlerContext<Host = null> extends HandlerContextBase<Host> \{$/m);
    assert.match(out, /^export interface ChannelHandlerContext<Host = null, Carrier extends 'port' \| 'local' = 'port' \| 'local'> extends HandlerContextBase<Host> \{$/m);
    assert.match(out, /^export type HandlerContext<Host = null, Carrier extends CarrierName = 'http'> = Extract<HttpHandlerContext<Host> \| ChannelHandlerContext<Host, 'port'> \| ChannelHandlerContext<Host, 'local'>, \{ carrier: Carrier \}>;$/m);
  });

  it('declares the byte surface: ByteOperations holds exactly the opaque operations, and HttpClient extends Client with bytes over them', () => {
    assert.match(out, /^export interface ByteOperations \{\n {2}'image\.bytes': ImageBytesInput;\n\}/m, 'the one opaque operation, and nothing else');
    assert.match(out, /^export interface ByteContext \{ signal\?: AbortSignal; attempt\?: unknown; headers\?: Record<string, string>; ifNoneMatch\?: string; ifMatch\?: string; body\?: string \| Uint8Array \| ReadableStream<Uint8Array> \| AsyncIterable<Uint8Array> \| null \}$/m);
    assert.match(out, /^export type ByteResponse = \{ status: number; headers: Record<string, string>; media: string \| null; body: ReadableStream<Uint8Array> \| null \};$/m);
    assert.match(out, /^export interface HttpClient extends Client \{\n {2}bytes<K extends keyof ByteOperations>\(op: K, input: ByteOperations\[K\], ctx\?: ByteContext\): Promise<Outcome<ByteResponse>>;\n\}/m);
    assert.doesNotMatch(out, /^export interface Client \{[^}]*bytes/m, 'the binding-neutral Client carries no byte method');
    // a contract without an opaque operation declares an EMPTY ByteOperations: bytes is uncallable, never absent
    const none = toTypeScript(compileContract({ $contract: '0.1', operations: { a: { kind: 'read', output: true } } }), { banner: false });
    assert.match(none, /^export interface ByteOperations \{\n\}/m);
  });

  it('types an input-less operation as null, keeps names unique under collisions, and leaves server operations out', () => {
    const contract = compileContract({
      $contract: '0.1',
      // ThingPutInput is REACHABLE (thing.get's output references it), so
      // the operation type of thing.put must step aside; an UNREACHABLE
      // def never enters the projection and never takes a name
      $defs: { ThingPutInput: { type: 'string' }, Unreachable: { type: 'boolean' }, Shared: { type: 'object', properties: { n: { type: 'integer' } } } },
      operations: {
        'thing.get': { kind: 'read', output: { $ref: '#/$defs/ThingPutInput' }, http: { method: 'GET', path: '/t' } },
        'thing.put': { kind: 'command', input: { type: 'object', properties: { x: { $ref: '#/$defs/Shared' } } }, output: { $ref: '#/$defs/Shared' } },
        'no.input': { kind: 'read', output: { type: 'object' }, http: { method: 'GET', path: '/n' } },
        'only.server': { kind: 'read', output: true, policy: { audience: 'server' }, http: { method: 'GET', path: '/s' } },
      },
    });
    const ts = toTypeScript(contract, { banner: false });
    assert.match(ts, /^export type ThingPutInput = string;$/m, 'the contract\'s own reachable def keeps its name');
    assert.match(ts, /'thing\.put': \{ kind: 'command'; input: ThingPutInput2; output: ThingPutOutput; errors: never \};/);
    assert.match(ts, /^export interface ThingPutInput2 \{/m);
    assert.match(ts, /^export type ThingPutOutput = Shared;$/m);
    assert.match(ts, /'thing\.get': \{ kind: 'read'; input: null; output: ThingGetOutput; errors: never \};/);
    assert.match(ts, /^export type ThingGetOutput = ThingPutInput;$/m);
    assert.match(ts, /'no\.input': \{ kind: 'read'; input: null; output: NoInputOutput; errors: never \};/);
    assert.match(ts, /^ {2}'no\.input': null;$/m);
    assert.doesNotMatch(ts, /only\.server|OnlyServer|Unreachable/);
    assert.strictEqual((ts.match(/^export interface Shared \{/gm) ?? []).length, 1, 'a shared $defs entry is declared once');
  });
});

describe('toTypeScript — the DateTime brand (§12.3)', () => {
  /** @param {any} properties */
  const one = (properties) => compileContract({
    $contract: '0.1',
    operations: {
      a: {
        kind: 'command',
        input: { type: 'object', properties },
        output: true,
      },
    },
  });

  it('declares the brand once and references it from every position', () => {
    const out = toTypeScript(one({
      at: { type: 'string', format: 'date-time' },
      on: { type: 'string', format: 'date' },
      stamps: { type: 'array', items: { type: 'string', format: 'date-time' } },
      nested: { type: 'object', properties: { seen: { type: 'string', format: 'date' } } },
    }), { banner: false });
    assert.strictEqual(out.match(/export type DateTime =/g)?.length, 1, 'declared once');
    assert.match(out, /export type DateTime = string & \{ __jarenTag: "date-time"; \};/);
    assert.match(out, /at\?: DateTime;/);
    assert.match(out, /on\?: DateTime;/);
    assert.match(out, /stamps\?: Array<DateTime>;/);
    assert.match(out, /seen\?: DateTime;/, 'a nested member carries it too');
    assert.doesNotMatch(out, /format="date/, 'the brand expresses the format; it is no longer a dropped constraint');
  });

  it('brands a nullable date as the brand or null', () => {
    const out = toTypeScript(one({ at: { type: ['string', 'null'], format: 'date-time' } }), { banner: false });
    assert.match(out, /at\?: DateTime \| null;/);
  });

  it('a document with no date carries no brand declaration', () => {
    const out = toTypeScript(one({ name: { type: 'string' } }), { banner: false });
    assert.doesNotMatch(out, /DateTime/);
  });

  it('a contract that declares its own DateTime keeps it; the brand takes the next free name', () => {
    const out = toTypeScript(compileContract({
      $contract: '0.1',
      $defs: { DateTime: { type: 'object', properties: { epoch: { type: 'integer' } } } },
      operations: {
        a: {
          kind: 'command',
          input: {
            type: 'object',
            properties: { at: { type: 'string', format: 'date-time' }, own: { $ref: '#/$defs/DateTime' } },
          },
          output: true,
        },
      },
    }), { banner: false });
    assert.match(out, /export type DateTime2 = string & \{ __jarenTag: "date-time"; \};/);
    assert.match(out, /export interface DateTime \{/, "the contract's own definition keeps its name");
    assert.match(out, /at\?: DateTime2;/);
    assert.match(out, /own\?: DateTime;/);
  });
});

